// BancoPerguntasEstudoDoMeio.js - MENONGUE EDUCA
window.BancoPerguntasEstudoDoMeio = [
    // 1ª CLASSE (20 questões)
    { pergunta: "Como se chama o lugar onde vivemos com a nossa família?", opcoes: ["Escola", "Casa", "Hospital", "Mercado"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quem faz parte da nossa família?", opcoes: ["Amigos", "Pais e irmãos", "Professores", "Vizinhos"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que devemos fazer antes de comer?", opcoes: ["Brincar", "Lavar as mãos", "Dormir", "Gritar"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Onde devemos deitar o lixo?", opcoes: ["No chão", "No rio", "No caixote do lixo", "Na rua"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é o nome da nossa escola?", opcoes: ["Minha Escola", "Hospital", "Esquadra", "Igreja"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Como se chama o nosso país?", opcoes: ["Angola", "Brasil", "Portugal", "Namíbia"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a cor da bandeira de Angola (partes principais)?", opcoes: ["Verde e Branco", "Vermelho e Preto", "Azul e Amarelo", "Rosa"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que usamos para tomar banho?", opcoes: ["Terra", "Água e Sabão", "Sumo", "Papel"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Como cumprimentamos o professor de manhã?", opcoes: ["Boa noite", "Boa tarde", "Bom dia", "Adeus"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quem cuida de nós quando estamos doentes em casa?", opcoes: ["Polícia", "Nossa família", "Bombeiros", "Piloto"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que fazemos na escola?", opcoes: ["Dormir o dia todo", "Aprender e brincar", "Tomar banho", "Cozinhar"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes é um animal que vive em casa?", opcoes: ["Leão", "Gato", "Elefante", "Jacaré"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que devemos fazer ao atravessar a rua?", opcoes: ["Correr sem olhar", "Olhar para os dois lados", "Fechar os olhos", "Brincar"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual o nome da cidade onde moramos?", opcoes: ["Luanda", "Menongue", "Lobito", "Namibe"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Onde compramos o pão?", opcoes: ["Na farmácia", "Na padaria", "No hospital", "Na escola"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quem é o pai do nosso pai?", opcoes: ["Tio", "Avô", "Irmão", "Primo"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que usamos para escovar os dentes?", opcoes: ["Pente", "Escova e pasta", "Sabonete", "Colher"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a roupa que usamos para ir à escola?", opcoes: ["Pijama", "Uniforme/Bata", "Fato de banho", "Capa"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O sol brilha durante o...?", opcoes: ["Dia", "Noite", "Almoço", "Jantar"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "As estrelas aparecem durante a...?", opcoes: ["Manhã", "Tarde", "Noite", "Merenda"], correta: 2, grupoClasse: "1", nivel: "basico" },

    // 2ª CLASSE (20 questões)
    { pergunta: "Quais são os órgãos dos sentidos?", opcoes: ["Mãos e pés", "Visão, audição, paladar, olfacto e tacto", "Cabelo e unhas", "Dentes e língua"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Para que serve a higiene?", opcoes: ["Para ficar sujo", "Para ter saúde", "Para brincar", "Para dormir"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é uma comunidade?", opcoes: ["Um grupo de pessoas que vivem juntas", "Uma pessoa sozinha", "Um deserto", "Uma floresta"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destes é um meio de transporte terrestre?", opcoes: ["Barco", "Avião", "Carro", "Canoa"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que devemos fazer para evitar doenças?", opcoes: ["Não lavar as mãos", "Lavar os alimentos e as mãos", "Comer lixo", "Andar descalço na lama"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é o símbolo nacional de Angola?", opcoes: ["Bandeira Nacional", "Um brinquedo", "Um carro", "Uma casa"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quem dirige o avião?", opcoes: ["Motorista", "Piloto", "Maquinista", "Capitão"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Onde vive o peixe?", opcoes: ["No deserto", "Na água", "Nas árvores", "No ar"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é um meio de transporte aéreo?", opcoes: ["Bicicleta", "Avião", "Comboio", "Mota"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que o semáforo vermelho indica?", opcoes: ["Siga", "Pare", "Atenção", "Corra"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Como chamamos a nossa morada?", opcoes: ["Escola", "Endereço", "Nome", "Apelido"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destes é um animal doméstico?", opcoes: ["Leão", "Cão", "Tigre", "Lobo"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Para que serve o ouvido?", opcoes: ["Ver", "Ouvir", "Cheirar", "Tocar"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o nome do nosso planeta?", opcoes: ["Marte", "Terra", "Lua", "Sol"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quem é a irmã da nossa mãe?", opcoes: ["Avó", "Tia", "Prima", "Sobrinha"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é o pequeno-almoço?", opcoes: ["Refeição da noite", "Refeição da manhã", "Refeição do meio-dia", "Lanche"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Onde os comboios andam?", opcoes: ["Na estrada", "Na linha férrea", "Na água", "No ar"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destes é um meio de comunicação?", opcoes: ["Cadeira", "Televisão", "Colher", "Sapato"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que nasce da semente?", opcoes: ["Pedra", "Planta", "Brinquedo", "Vidro"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que usamos para ver as horas?", opcoes: ["Régua", "Relógio", "Bússola", "Termómetro"], correta: 1, grupoClasse: "2", nivel: "basico" },

    // 3ª CLASSE (20 questões)
    { pergunta: "Quais são as partes principais de uma planta?", opcoes: ["Só folhas", "Raiz, caule e folhas", "Só flores", "Tronco e ramos"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Como se chama o médico que cuida dos animais?", opcoes: ["Dentista", "Veterinário", "Pediatra", "Enfermeiro"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o ambiente?", opcoes: ["Tudo o que nos rodeia", "Só a escola", "Só a nossa casa", "Só as árvores"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é a capital de Angola?", opcoes: ["Menongue", "Luanda", "Benguela", "Huambo"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o relevo?", opcoes: ["As formas da superfície da terra", "O clima", "As plantas", "Os animais"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o rio que passa perto de Menongue?", opcoes: ["Rio Cuebe", "Rio Zaire", "Rio Kwanza", "Rio Cunene"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a agricultura?", opcoes: ["Criação de gado", "Cultivo da terra", "Pesca no mar", "Construção de casas"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que são animais vertebrados?", opcoes: ["Têm ossos", "Não têm ossos", "Vivem no ar", "Têm 8 patas"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é o principal alimento do bebê?", opcoes: ["Arroz", "Leite", "Feijão", "Carne"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o clima?", opcoes: ["Estado do tempo numa região", "O solo", "As montanhas", "Os rios"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quais são as estações do ano em Angola?", opcoes: ["Primavera e Verão", "Seca (Cacimbo) e Chuvosa", "Inverno e Outono", "Neve e Sol"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a pecuária?", opcoes: ["Cultivo de milho", "Criação de animais", "Pesca de peixe", "Mineração"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Para que serve o esqueleto?", opcoes: ["Para comer", "Sustentação do corpo", "Para pensar", "Para ver"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o solo?", opcoes: ["O ar", "A camada da terra onde as plantas crescem", "A água do mar", "O núcleo da terra"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o maior país de África em área?", opcoes: ["Angola", "Argélia", "Nigéria", "Egipto"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o comércio?", opcoes: ["Plantar árvores", "Compra e venda de produtos", "Fazer ginástica", "Pescar"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a poluição do ar?", opcoes: ["Ar puro", "Ar com fumaça e gases tóxicos", "Vento forte", "Ar condicionado"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o órgão que usamos para pensar?", opcoes: ["Coração", "Cérebro", "Estômago", "Pulmão"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a reciclagem?", opcoes: ["Jogar fora", "Reaproveitar materiais", "Queimar lixo", "Esconder lixo"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual a função do coração?", opcoes: ["Digerir", "Bombear o sangue", "Respirar", "Ouvir"], correta: 1, grupoClasse: "3", nivel: "basico" },

    // 4ª CLASSE (20 questões)
    { pergunta: "Em que província fica a cidade de Menongue?", opcoes: ["Bié", "Cuando Cubango", "Huíla", "Cunene"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que são animais domésticos?", opcoes: ["Vivem na floresta", "Vivem com os humanos", "Vivem no mar", "Voam"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quais são os pontos cardeais?", opcoes: ["Norte, Sul, Este e Oeste", "Cima e Baixo", "Frente e Trás", "Direita e Esquerda"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é um recurso natural?", opcoes: ["Algo feito na fábrica", "Algo que vem da natureza", "Um brinquedo", "Um computador"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a democracia?", opcoes: ["Poder de um só", "Poder do povo/voto", "Guerra", "Sem governo"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quem proclamou a independência de Angola?", opcoes: ["Jonas Savimbi", "Agostinho Neto", "José Eduardo", "Holden Roberto"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a hidrografia?", opcoes: ["Estudo do solo", "Estudo das águas/rios", "Estudo do ar", "Estudo das estrelas"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o rio mais longo de Angola?", opcoes: ["Rio Kwanza", "Rio Cunene", "Rio Zambeze", "Rio Zaire"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o sistema solar?", opcoes: ["Conjunto de estrelas", "Sol e planetas que giram em volta", "Apenas a lua", "Uma galáxia distante"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a fauna?", opcoes: ["Conjunto de plantas", "Conjunto de animais", "Conjunto de pedras", "Conjunto de nuvens"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a flora?", opcoes: ["Conjunto de animais", "Conjunto de plantas/vegetação", "Conjunto de rios", "Conjunto de montanhas"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o dia da Independência de Angola?", opcoes: ["11 de Novembro", "4 de Fevereiro", "25 de Dezembro", "1 de Maio"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o estado de saúde?", opcoes: ["Estar doente", "Bem-estar físico, mental e social", "Ter muito dinheiro", "Correr muito"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a exportação?", opcoes: ["Comprar de fora", "Vender produtos para outros países", "Plantar milho", "Fazer pão"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é a principal riqueza mineral de Angola?", opcoes: ["Ouro", "Petróleo e Diamantes", "Carvão", "Prata"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a atmosfera?", opcoes: ["Água da terra", "Camada de gases que envolve a terra", "O solo", "O núcleo"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é um município?", opcoes: ["Uma casa", "Divisão administrativa de uma província", "Um país inteiro", "Um continente"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a higiene mental?", opcoes: ["Lavar o cabelo", "Cuidar da saúde dos pensamentos/mente", "Comer muito", "Dormir pouco"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o maior oceano que banha Angola?", opcoes: ["Índico", "Atlântico", "Pacífico", "Ártico"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o turismo?", opcoes: ["Trabalhar na lavra", "Viajar por prazer ou estudo", "Ficar em casa", "Limpar a rua"], correta: 1, grupoClasse: "4", nivel: "basico" },

    // 5ª CLASSE (20 questões)
    { pergunta: "O que estuda a Geografia?", opcoes: ["O passado", "O espaço e a relação homem-natureza", "Os números", "As letras"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é o continente onde fica Angola?", opcoes: ["Europa", "África", "Ásia", "América"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a cartografia?", opcoes: ["Estudo das cartas", "Arte de desenhar mapas", "Estudo dos carros", "Estudo das pedras"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a densidade populacional?", opcoes: ["Peso das pessoas", "Número de habitantes por km²", "Tamanho das casas", "Riqueza de um povo"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o IDH?", opcoes: ["Índice de Desenvolvimento Humano", "Imposto sobre carros", "Nome de um rio", "Tipo de solo"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o país mais populoso do mundo atualmente?", opcoes: ["Brasil", "Índia/China", "Angola", "EUA"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a globalização?", opcoes: ["Integração mundial econômica e cultural", "Fim do mundo", "Viagem espacial", "Plantar árvores"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a desertificação?", opcoes: ["Plantar florestas", "Transformação de terras em deserto", "Fazer praias", "Chover muito"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o efeito estufa?", opcoes: ["Um jardim frio", "Retenção de calor na atmosfera", "Um tipo de casa", "Vento solar"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a função da ONU?", opcoes: ["Fazer guerras", "Manter a paz e segurança mundial", "Vender petróleo", "Explorar o espaço"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o desenvolvimento sustentável?", opcoes: ["Gastar tudo", "Usar recursos sem esgotar para o futuro", "Cortar árvores", "Poluir rios"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a biosfera?", opcoes: ["Camada de rochas", "Esfera da vida na terra", "Camada de água", "Camada de ar"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é migração?", opcoes: ["Ficar parado", "Deslocamento de pessoas entre regiões", "Dormir", "Cantar"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a indústria?", opcoes: ["Plantar milho", "Transformação de matéria-prima em produtos", "Vender frutas na rua", "Pescar"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a moeda oficial de Angola?", opcoes: ["Dólar", "Kwanza", "Euro", "Real"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a balança comercial?", opcoes: ["Balança de pesar comida", "Relação entre exportação e importação", "Preço do ouro", "Tamanho do mercado"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o relevo de planalto?", opcoes: ["Terreno plano e baixo", "Terreno elevado e plano no topo", "Montanha pontiaguda", "Buraco fundo"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a hidrografia de uma região?", opcoes: ["Suas estradas", "Seus rios e lagos", "Suas montanhas", "Seus animais"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o clima tropical?", opcoes: ["Muito frio e neve", "Quente com épocas de chuva", "Sempre gelado", "Sem sol"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a importância da floresta do Maiombe?", opcoes: ["Produzir diamantes", "Biodiversidade e regulação do clima", "Lugar para desertos", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },

    // 6ª CLASSE (20 questões)
    { pergunta: "O que foi a Conferência de Berlim?", opcoes: ["Festa na Alemanha", "Partilha de África pelos europeus", "Invenção do rádio", "Guerra mundial"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual é o principal objetivo da União Africana?", opcoes: ["Unir os países de África e promover o desenvolvimento", "Fazer comércio com Marte", "Dividir o continente", "Nada"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o colonialismo?", opcoes: ["Amizade entre povos", "Domínio político e económico de um povo sobre outro", "Turismo", "Liberdade"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o neo-colonialismo?", opcoes: ["Novo tipo de planta", "Nova forma de domínio indireto", "Fim da escravidão", "Paz mundial"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que caracteriza um país em desenvolvimento?", opcoes: ["Muita riqueza e tecnologia", "Economia em crescimento e desafios sociais", "País mais rico do mundo", "País sem pessoas"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a biodiversidade?", opcoes: ["Apenas plantas", "Variedade de todas as formas de vida", "Apenas animais", "Apenas humanos"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a desertificação?", opcoes: ["Aumento das florestas", "Degradação da terra em zonas secas", "Inundação", "Neve"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o papel da mulher na sociedade atual?", opcoes: ["Apenas ficar em casa", "Igualdade de direitos e participação em todas as áreas", "Não deve estudar", "Não deve trabalhar"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que são direitos humanos?", opcoes: ["Direitos de alguns", "Direitos básicos de todos os seres humanos", "Leis de um país apenas", "Regras de um jogo"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a corrupção?", opcoes: ["Ato honesto", "Uso ilegal do poder para benefício próprio", "Trabalhar muito", "Ajudar os outros"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a cidadania?", opcoes: ["Morar numa cidade", "Conjunto de direitos e deveres de um indivíduo num Estado", "Ter um carro", "Saber ler apenas"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o PIB?", opcoes: ["Produto Interno Bruto (soma das riquezas)", "Plano Interno de Bens", "País Incrível e Belo", "Imposto de Bens"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a inflação?", opcoes: ["Aumento dos preços", "Queda dos preços", "Dinheiro infinito", "Fim do mercado"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a pirâmide etária?", opcoes: ["Monumento no Egito", "Gráfico que mostra a idade da população", "Forma de uma montanha", "Lista de reis"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que são fontes de energia limpa?", opcoes: ["Petróleo", "Solar, Eólica e Hídrica", "Carvão", "Gás"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a UNESCO?", opcoes: ["Banco mundial", "Organização para Educação, Ciência e Cultura", "Fábrica de carros", "Loja de roupas"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a importância de preservar monumentos históricos?", opcoes: ["Gastas dinheiro", "Manter viva a memória e cultura de um povo", "Nada", "Fazer casas novas no lugar"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a ética?", opcoes: ["Conjunto de valores morais e princípios", "Um tipo de comida", "Uma dança", "Uma cor"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o maior desafio ambiental do século XXI?", opcoes: ["Falta de papel", "Alterações climáticas e poluição", "Falta de brinquedos", "Excesso de sol"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o patriotismo?", opcoes: ["Odiar outros países", "Amor e respeito pela própria pátria", "Não pagar impostos", "Não respeitar a bandeira"], correta: 1, grupoClasse: "6", nivel: "basico" }
];
