// BancoPerguntasHistoria.js - MENONGUE EDUCA
window.BancoPerguntasHistoria = [
    // 1ª CLASSE (20 questões)
    { pergunta: "Em que país vivemos?", opcoes: ["Portugal", "Angola", "Brasil", "Namíbia"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a cor da nossa bandeira que representa o sangue?", opcoes: ["Amarelo", "Preto", "Vermelho", "Azul"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a capital de Angola?", opcoes: ["Menongue", "Luanda", "Benguela", "Huambo"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quem é o Fundador da Nação Angolana?", opcoes: ["Savimbi", "Agostinho Neto", "Holden", "Mandume"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que festejamos no dia 11 de Novembro?", opcoes: ["Natal", "Independência", "Paz", "Carnaval"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a cor que representa o povo africano na bandeira?", opcoes: ["Branco", "Preto", "Verde", "Azul"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Como se chama o nosso primeiro presidente?", opcoes: ["João Lourenço", "Agostinho Neto", "José Eduardo", "Savimbi"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual o nome da nossa província?", opcoes: ["Bié", "Cuando Cubango", "Huíla", "Cunene"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Onde fica a sede do governo de Angola?", opcoes: ["Luanda", "Menongue", "Lobito", "Huambo"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é o símbolo amarelo no meio da bandeira?", opcoes: ["Uma estrela", "Catana e Roda dentada", "Um sol", "Uma lua"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que é a Pátria?", opcoes: ["Uma loja", "A nossa terra/país", "Um brinquedo", "Uma escola"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual o dia em que se celebra a Paz em Angola?", opcoes: ["1 de Janeiro", "4 de Abril", "25 de Dezembro", "1 de Maio"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quem é o atual Presidente de Angola?", opcoes: ["Agostinho Neto", "João Lourenço", "José Eduardo", "Manuel Vicente"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual a língua oficial de Angola?", opcoes: ["Inglês", "Português", "Francês", "Espanhol"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O hino nacional chama-se 'Angola... '?", opcoes: ["Avante", "Sempre", "Querida", "Livre"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "A moeda nacional é o...?", opcoes: ["Dólar", "Kwanza", "Euro", "Real"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quantas cores principais tem a bandeira de Angola?", opcoes: ["2", "3", "4", "5"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O dia da Independência é em que mês?", opcoes: ["Setembro", "Novembro", "Dezembro", "Janeiro"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quem protege as nossas fronteiras?", opcoes: ["Professores", "Exército/FAA", "Alunos", "Cozinheiros"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "A paz é importante para o país?", opcoes: ["Sim", "Não", "Talvez", "Só para alguns"], correta: 0, grupoClasse: "1", nivel: "basico" },

    // 2ª CLASSE (20 questões)
    { pergunta: "Qual é o nome da nossa província?", opcoes: ["Bié", "Cuando Cubango", "Huíla", "Cunene"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quem é o atual Presidente de Angola?", opcoes: ["Agostinho Neto", "José Eduardo", "João Lourenço", "Manuel Vicente"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que representa o preto na bandeira de Angola?", opcoes: ["O sol", "O continente africano", "O sangue", "A riqueza"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é a moeda de Angola?", opcoes: ["Dólar", "Kwanza", "Euro", "Real"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Como se chama o monumento em Luanda dedicado ao primeiro Presidente?", opcoes: ["Memorial Agostinho Neto", "Torre Eiffel", "Cristo Rei", "Estátua da Liberdade"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o dia do Herói Nacional?", opcoes: ["4 de Fevereiro", "17 de Setembro", "11 de Novembro", "25 de Maio"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que se comemora a 4 de Janeiro?", opcoes: ["Dia da Independência", "Mártires da Baixa de Cassanje", "Dia da Paz", "Natal"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quem escreveu o hino nacional?", opcoes: ["Rui Mingas", "Manuel Rui Monteiro", "Agostinho Neto", "Holden Roberto"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é a capital da nossa província?", opcoes: ["Cuchi", "Menongue", "Cuito Cuanavale", "Mavinga"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "A flor nacional de Angola é a...?", opcoes: ["Rosa", "Welwitschia Mirabilis", "Margarida", "Girassol"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quem foi a Rainha Ginga?", opcoes: ["Uma cantora", "Uma heroína que lutou contra o colonialismo", "Uma médica", "Uma professora"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que significa a palavra 'Independência'?", opcoes: ["Estar preso", "Ser livre/Autonomia", "Fazer guerra", "Ter dinheiro"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o nome do rio mais famoso de Angola?", opcoes: ["Rio Nilo", "Rio Kwanza", "Rio Amazonas", "Rio Mississipi"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O dia 25 de Maio é o dia de quê?", opcoes: ["Angola", "África", "Mundo", "Mulher"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o animal símbolo da nossa seleção de futebol?", opcoes: ["Leão", "Palanca Negra", "Elefante", "Zebra"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Onde nasceu Agostinho Neto?", opcoes: ["Ícolo e Bengo", "Benguela", "Huambo", "Namibe"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o nome da nossa língua nacional principal no Cuando Cubango?", opcoes: ["Umbundu", "Nganguela", "Kimbundu", "Cokwe"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que representa o vermelho na bandeira?", opcoes: ["Ouro", "Sangue derramado pela liberdade", "As matas", "O céu"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que representa a estrela na bandeira?", opcoes: ["Um prêmio", "Solidariedade internacional", "Uma luz no caminho", "A lua"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que devemos fazer durante o hino nacional?", opcoes: ["Correr e gritar", "Estar em posição de respeito (sentido)", "Sentar e comer", "Dormir"], correta: 1, grupoClasse: "2", nivel: "basico" },

    // 3ª CLASSE (20 questões)
    { pergunta: "O que aconteceu em 4 de Fevereiro de 1961?", opcoes: ["Fim da guerra", "Início da Luta Armada", "Independência", "Paz"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é a capital da província do Cuando Cubango?", opcoes: ["Luanda", "Cuito Cuanavale", "Menongue", "Mavinga"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quem foi a Rainha que lutou contra a ocupação colonial?", opcoes: ["Rainha Ginga", "Rainha Isabel", "Rainha Vitória", "Rainha Ana"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é o principal rio que atravessa a cidade de Menongue?", opcoes: ["Rio Kwanza", "Rio Cuebe", "Rio Zaire", "Rio Cunene"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Em que ano Angola tornou-se independente?", opcoes: ["1961", "1974", "1975", "2002"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual era o nome de Angola antes de ser independente?", opcoes: ["Reino do Congo", "Província Ultramarina de Angola", "Brasil", "Namíbia"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quem foi o Rei Mandume?", opcoes: ["Um músico", "Rei dos Cuanhamas que resistiu aos colonos", "Um escritor", "Um piloto"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o 'Elinga'?", opcoes: ["Uma dança", "Palavra umbundu que significa 'lugar de aprendizagem'", "Um prato", "Um rio"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual foi o papel dos missionários na história?", opcoes: ["Fazer guerra", "Educação e evangelização", "Vender armas", "Pescar"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que se produzia muito em Angola no passado?", opcoes: ["Café, Algodão e Sisal", "Gelados", "Televisores", "Carros"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Em que cidade foi proclamada a independência de Angola?", opcoes: ["Benguela", "Luanda", "Huambo", "Menongue"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quem foi o sucessor de Agostinho Neto?", opcoes: ["João Lourenço", "José Eduardo dos Santos", "Savimbi", "Holden Roberto"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a 'Baixa de Cassanje'?", opcoes: ["Uma montanha", "Local de um massacre e revolta de camponeses", "Uma praia", "Uma floresta"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual a importância do Caminho de Ferro de Benguela?", opcoes: ["Levar pessoas à lua", "Transporte de minérios e pessoas", "Fazer corridas", "Nada"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quem eram os 'Contratados'?", opcoes: ["Turistas", "Trabalhadores forçados no tempo colonial", "Políticos", "Soldados"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que representava a 'Palanca Negra Gigante'?", opcoes: ["Um boi comum", "Animal raro e símbolo de Angola", "Um gato", "Um pássaro"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual era a principal atividade dos povos antigos de Angola?", opcoes: ["Agricultura, Pesca e Metalurgia", "Internet", "Aviação", "Indústria de luxo"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quem foi Ngola Kiluanje?", opcoes: ["Um caçador", "Um grande soberano do Reino do Ndongo", "Um marinheiro", "Um cozinheiro"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o 'Kimbanguismo'?", opcoes: ["Uma dança", "Um movimento religioso africano", "Um tipo de comida", "Um desporto"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o porto principal de Angola no Sul?", opcoes: ["Porto de Luanda", "Porto do Namibe", "Porto do Soyo", "Porto de Cabinda"], correta: 1, grupoClasse: "3", nivel: "basico" },

    // 4ª CLASSE (20 questões)
    { pergunta: "O que se comemora no dia 4 de Abril em Angola?", opcoes: ["Independência", "Dia da Paz", "Dia do Herói Nacional", "Dia da Criança"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o nome do primeiro Presidente de Angola?", opcoes: ["José Eduardo", "António Agostinho Neto", "João Lourenço", "Manuel Vicente"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Como se chama a árvore que é símbolo nacional de Angola?", opcoes: ["Palmeira", "Embondeiro", "Pinheiro", "Eucalipto"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o animal que aparece no brasão de Angola?", opcoes: ["Leão", "Palanca Negra", "Elefante", "Águia"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Em que dia se comemora o dia do Herói Nacional?", opcoes: ["11 de Novembro", "17 de Setembro", "4 de Fevereiro", "25 de Dezembro"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a importância da Batalha do Cuito Cuanavale?", opcoes: ["Festa regional", "Ponto de viragem na guerra e fim do Apartheid na Namíbia", "Início do carnaval", "Nada"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o 'Mbanza Kongo'?", opcoes: ["Um mercado", "Capital do antigo Reino do Congo e Património Mundial", "Uma dança", "Um rio"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quem fundou a cidade de Luanda?", opcoes: ["Agostinho Neto", "Paulo Dias de Novais", "Diogo Cão", "Vasco da Gama"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual era a função da Catana na bandeira de Angola?", opcoes: ["Cortar pão", "Representar os camponeses e a luta armada", "Decoração", "Brinquedo"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é a função da Roda Dentada na bandeira?", opcoes: ["Parte de um carro", "Representar os operários e a indústria", "Um relógio", "Uma jóia"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quem foi o navegador português que chegou à foz do Rio Zaire?", opcoes: ["Vasco da Gama", "Diogo Cão", "Pedro Álvares Cabral", "Magalhães"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que foi o 'Tráfico de Escravos'?", opcoes: ["Turismo antigo", "Venda forçada de africanos para as Américas", "Troca de livros", "Comércio de sal"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que representava o Reino da Lunda?", opcoes: ["Um pequeno jardim", "Um vasto império no Leste de Angola conhecido pela sua organização", "Uma ilha", "Um deserto"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o nome do poeta maior de Angola?", opcoes: ["Camões", "Agostinho Neto", "Fernando Pessoa", "Jorge Amado"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que se celebra a 2 de Março?", opcoes: ["Dia da Mulher Angolana", "Dia do Pai", "Dia da Independência", "Dia do Professor"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a província de Angola com maior número de diamantes?", opcoes: ["Luanda", "Lunda Norte", "Huíla", "Namibe"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a 'Insignia da República'?", opcoes: ["Um selo de carta", "Brasão de armas e símbolo da soberania", "Um brinquedo", "Uma roupa"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Em que ano Angola entrou para a ONU?", opcoes: ["1975", "1976", "1980", "2000"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quem foi Njinga Mbandi?", opcoes: ["Uma rainha guerreira que defendeu a soberania angolana", "Uma bailarina", "Uma escritora", "Uma pintora"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a importância de Menongue na história do Sul?", opcoes: ["Nenhuma", "Centro logístico e de resistência importante", "Apenas uma vila pequena", "Nada"], correta: 1, grupoClasse: "4", nivel: "basico" },

    // 5ª CLASSE (20 questões)
    { pergunta: "A Batalha do Cuito Cuanavale é importante para qual região?", opcoes: ["Norte de África", "África Austral", "Europa", "América"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quem foi o soberano do Reino do Ndongo?", opcoes: ["Rei Mandume", "Rei Ngola Kiluanje", "Rei Ekuikui", "Rei Catyavala"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Em que ano foi assinado o Memorando de Entendimento do Luena (Paz)?", opcoes: ["1975", "1992", "2002", "2010"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual era a antiga capital de Angola antes de Luanda?", opcoes: ["Benguela", "São Salvador (Mbanza Kongo)", "Huambo", "Namibe"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que foi a Conferência de Berlim (1884-1885)?", opcoes: ["Descoberta de ouro", "Partilha de África", "Fim da escravidão", "Invenção da luz"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o papel dos movimentos de libertação (MPLA, FNLA, UNITA)?", opcoes: ["Lutar pela independência de Angola", "Fazer comércio", "Plantar milho", "Nada"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que foi o Acordo de Alvor?", opcoes: ["Acordo de paz entre tribos", "Acordo para a descolonização e independência de Angola", "Tratado de comércio", "Fim da 1ª guerra"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quem foi Ekuikui II?", opcoes: ["Um médico", "Rei do Bailundo (Reino de Ovimbundu)", "Um marinheiro", "Um piloto"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a importância da exploração do petróleo em Cabinda?", opcoes: ["Nenhuma", "Principal fonte de receitas do Estado", "Fazer plástico", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que representava a 'Assembleia Nacional'?", opcoes: ["Uma casa de festas", "Poder legislativo e representação do povo", "Um museu", "Um cinema"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que foi a 'Guerra Civil' em Angola?", opcoes: ["Um jogo", "Conflito interno após a independência por poder político", "Uma invasão estrangeira apenas", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quem foi o mediador da paz em Angola?", opcoes: ["Apenas angolanos", "Governo angolano, UNITA e comunidade internacional", "Países europeus apenas", "EUA sozinhos"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a província conhecida como 'Planalto Central'?", opcoes: ["Luanda", "Huambo", "Namibe", "Zaire"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a 'Lusofonia'?", opcoes: ["Medo de luz", "Comunidade de países que falam português", "Um prato típico", "Uma dança"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a importância da educação no período pós-independência?", opcoes: ["Nenhuma", "Erradicação do analfabetismo e formação de quadros", "Só para ricos", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quem foi Mutu-ya-Kevela?", opcoes: ["Um bailarino", "Líder da resistência no Planalto Central (Bailundo)", "Um músico", "Um poeta"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que são 'Línguas Nacionais'?", opcoes: ["Línguas estrangeiras", "Línguas de origem africana faladas em Angola", "Línguas inventadas", "Gírias"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a função do Banco Nacional de Angola?", opcoes: ["Emprestar livros", "Gerir a política monetária e o Kwanza", "Vender carros", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a 'Reconciliação Nacional'?", opcoes: ["Fazer mais guerra", "União e perdão entre os angolanos após o conflito", "Dividir o país", "Sair de Angola"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o maior desafio de Angola após a Paz de 2002?", opcoes: ["Dormir", "Reconstrução nacional e desenvolvimento económico", "Fazer festas", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },

    // 6ª CLASSE (20 questões)
    { pergunta: "Qual foi o papel de Agostinho Neto na OUA?", opcoes: ["Fundador", "Secretário", "Um dos impulsionadores", "Opositor"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que significa SADC?", opcoes: ["Sistema de Ajuda da China", "Comunidade para o Desenvolvimento da África Austral", "Sociedade de Angola e Congo", "Sindicato Africano de Cultura"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Em que ano se realizaram as primeiras eleições multipartidárias em Angola?", opcoes: ["1975", "1991", "1992", "2008"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual é a organização mundial da qual Angola faz parte desde 1976?", opcoes: ["OTAN", "ONU", "União Europeia", "Mercosul"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quem foi Mandume ya Ndemufayo?", opcoes: ["Um pintor", "Um rei Cuanhama que resistiu ao colonialismo", "Um músico", "Um navegador"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que foi o Processo de Bicesse?", opcoes: ["Acordo de pesca", "Acordos de paz que previam eleições e exército único", "Tratado de comércio", "Fim da ONU"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o 'Protocolo de Lusaka'?", opcoes: ["Um manual de escola", "Acordo de paz assinado na Zâmbia em 1994", "Uma lei de trânsito", "Uma receita"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a importância da diversificação da economia?", opcoes: ["Depender apenas do petróleo", "Criar novas fontes de riqueza além do petróleo", "Não trabalhar", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o Património Cultural?", opcoes: ["Dinheiro no banco", "Bens materiais e imateriais que contam a história de um povo", "Um brinquedo", "Uma roupa nova"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a função da União Africana (UA)?", opcoes: ["Fazer guerras", "Promover a integração e desenvolvimento do continente africano", "Dividir África", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que foi a 'Descolonização'?", opcoes: ["Chegada dos colonos", "Processo de saída das potências coloniais e independência", "Invenção do navio", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quem é considerado o 'Pai da Independência Namibianda' ajudado por Angola?", opcoes: ["Nelson Mandela", "Sam Nujoma", "Robert Mugabe", "Eduardo dos Santos"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que significa CPLP?", opcoes: ["Comunidade de Países de Língua Portuguesa", "Clube de Pessoas Livres e Poderosas", "Centro de Pesquisa de Luanda", "Nada"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a importância da 'Liberdade de Imprensa'?", opcoes: ["Nenhuma", "Direito de informar e ser informado sem censura", "Poder mentir à vontade", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a 'Soberania Nacional'?", opcoes: ["Ser mandado por outros", "Poder supremo de um Estado sobre o seu território", "Não ter governo", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quem foi o mediador da ONU em Angola (um dos mais famosos)?", opcoes: ["Margaret Anstee/Alioune Blondin Beye", "Cristiano Ronaldo", "Barack Obama", "Nada"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que representou a queda do Apartheid para Angola?", opcoes: ["Fim da ameaça externa do Sul e maior estabilidade regional", "Nada", "Início de nova guerra", "Mais frio"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a importância da reconstrução das infraestruturas?", opcoes: ["Gastar dinheiro", "Permitir o desenvolvimento e circulação de pessoas e bens", "Nada", "Fazer pó"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o 'Grito do Ipiranga' (comparação histórica)?", opcoes: ["Independência de Angola", "Independência do Brasil", "Um jogo de futebol", "Uma música"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o maior valor de um cidadão angolano?", opcoes: ["O egoísmo", "O amor à pátria, paz e trabalho", "A preguiça", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" }
];
