// BancoPerguntasMusica.js - MENONGUE EDUCA
window.BancoPerguntasMusica = [
    // 1ª CLASSE (20 questões)
    { pergunta: "Qual destes é um som da natureza?", opcoes: ["Carro", "Chuva", "Rádio", "Telemóvel"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que usamos para ouvir música?", opcoes: ["Olhos", "Ouvidos", "Mãos", "Pés"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes animais faz um som alto?", opcoes: ["Peixe", "Leão", "Borboleta", "Formiga"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Como se chama o som que fazemos com as mãos?", opcoes: ["Grito", "Palma", "Assobio", "Salto"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual instrumento é redondo e batemos nele?", opcoes: ["Flauta", "Tambor", "Violino", "Piano"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Cantar é usar a...?", opcoes: ["Mão", "Voz", "Perna", "Cabeça"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O apito faz um som...?", opcoes: ["Grave", "Agudo", "Baixo", "Longo"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que é o silêncio?", opcoes: ["Muito barulho", "Ausência de som", "Uma música", "Um grito"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes é um instrumento de sopro?", opcoes: ["Viola", "Flauta", "Batuque", "Piano"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O sino faz 'blem-blem'. Isso é um...?", opcoes: ["Desenho", "Som", "Cheiro", "Gosto"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quantas mãos usamos para tocar tambor?", opcoes: ["Nenhuma", "Uma ou duas", "Três", "Quatro"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que faz o maestro?", opcoes: ["Canta", "Dirige a música", "Toca flauta", "Dança sozinho"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é o som do gato?", opcoes: ["Miau", "Au-au", "Muuu", "Cocoricó"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O piano tem teclas pretas e...?", opcoes: ["Azuis", "Brancas", "Verdes", "Vermelhas"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "A música rápida dá vontade de...?", opcoes: ["Dormir", "Dançar", "Chorar", "Parar"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes é um brinquedo que faz música?", opcoes: ["Carrinho", "Xilofone de brinquedo", "Bola", "Corda"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O som do trovão é...?", opcoes: ["Fraco", "Forte/Grave", "Fininho", "Baixinho"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Podemos fazer música com o corpo?", opcoes: ["Não", "Sim", "Só com instrumentos", "Nunca"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a cor que lembra o som do mar (calma)?", opcoes: ["Vermelho", "Azul", "Preto", "Laranja"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "A música serve para...?", opcoes: ["Zangar", "Alegrias e festas", "Dormir apenas", "Não serve para nada"], correta: 1, grupoClasse: "1", nivel: "basico" },

    // 2ª CLASSE (20 questões)
    { pergunta: "O que é o ritmo?", opcoes: ["A letra", "O tempo da música", "O preço", "O lugar"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual instrumento é feito de madeira e tem cordas?", opcoes: ["Trombone", "Violão/Viola", "Pratos", "Flauta"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é um coro?", opcoes: ["Uma pessoa a cantar", "Muitas pessoas a cantar juntas", "Um tipo de couro", "Um tambor"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destes é o Hino de Angola?", opcoes: ["Angola Avante", "Minha Terra", "Hino da Paz", "Canto Livre"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "A flauta é feita geralmente de...?", opcoes: ["Papel", "Madeira ou plástico", "Pano", "Borracha"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é o volume na música?", opcoes: ["A velocidade", "A altura/força do som", "O nome da música", "O autor"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o nome do instrumento tradicional africano feito de cabaça?", opcoes: ["Violino", "Marimba", "Piano", "Saxofone"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Como se chama quem escreve músicas?", opcoes: ["Pintor", "Compositor", "Piloto", "Médico"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O som do violoncelo é...?", opcoes: ["Agudo", "Grave", "Curto", "Rápido"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que usamos para bater no tambor?", opcoes: ["Canetas", "Baquetas/Mãos", "Pés", "Pentes"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destes é um estilo de música angolana?", opcoes: ["Samba", "Semba", "Jazz", "Rock"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é melodia?", opcoes: ["O barulho das máquinas", "A sucessão de sons musicais", "O silêncio", "O peso do rádio"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual instrumento tem teclas?", opcoes: ["Flauta", "Piano", "Violão", "Batuque"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Onde se ensina música?", opcoes: ["Hospital", "Escola de Música/Conservatório", "Padaria", "Talho"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "A música clássica usa geralmente...?", opcoes: ["Só computadores", "Orquestras", "Só uma pessoa", "Nada"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o nome da pessoa que toca piano?", opcoes: ["Violinista", "Pianista", "Cantor", "Maestro"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O triângulo é um instrumento de...?", opcoes: ["Sopro", "Percussão", "Corda", "Teclado"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destes é um som desagradável?", opcoes: ["Música suave", "Ruído de britadeira", "Canto de pássaro", "Som da chuva"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Como guardamos a música hoje em dia?", opcoes: ["Em garrafas", "Em ficheiros digitais/CDs", "Em caixas de madeira", "Não se guarda"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o instrumento rei da orquestra?", opcoes: ["Tambor", "Violino", "Flauta", "Trompa"], correta: 1, grupoClasse: "2", nivel: "basico" },

    // 3ª CLASSE (20 questões)
    { pergunta: "O que são as notas musicais?", opcoes: ["Desenhos de animais", "Sinais que representam os sons", "Nomes de pessoas", "Números de telefone"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quantas são as notas musicais básicas?", opcoes: ["5", "7", "10", "12"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é a sequência correta?", opcoes: ["Do, Re, Mi, Fa, Sol, La, Si", "A, B, C, D, E", "Um, Dois, Três", "Azul, Verde, Amarelo"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a pauta ou pentagrama?", opcoes: ["Um instrumento", "Conjunto de 5 linhas onde se escreve a música", "Uma dança", "Um tipo de madeira"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual destes é um instrumento tradicional angolano?", opcoes: ["Piano", "Kissange", "Violino", "Oboé"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a clave de sol?", opcoes: ["Um tipo de sol", "Sinal colocado no início da pauta", "Um instrumento", "Uma nota musical"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Como se chama a intensidade do som?", opcoes: ["Duração", "Dinâmica (Forte/Piano)", "Altura", "Timbre"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é a função do metrônomo?", opcoes: ["Medir a temperatura", "Marcar o tempo/pulsação da música", "Aumentar o som", "Gravar a voz"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o timbre?", opcoes: ["O preço da música", "A característica que distingue um som do outro", "A velocidade", "A letra"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual instrumento é tocado com um arco?", opcoes: ["Guitarra", "Violino", "Tambor", "Piano"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é um compasso?", opcoes: ["Um objeto de desenho apenas", "Divisão do tempo musical em partes iguais", "Uma nota musical", "Um instrumento de sopro"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual destes instrumentos é de metal?", opcoes: ["Flauta de cana", "Trompete", "Batuque de madeira", "Violão"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que significa 'solo' na música?", opcoes: ["Música tocada por uma só pessoa", "Música tocada por todos", "O chão da sala", "Uma música rápida"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o nome da pele esticada no tambor?", opcoes: ["Pano", "Membrana", "Papel", "Vidro"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Como se chama o silêncio na partitura?", opcoes: ["Nota", "Pausa", "Ponto", "Traço"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O xilofone é um instrumento de...?", opcoes: ["Corda", "Lâminas (Percussão)", "Sopro", "Teclado"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual a diferença entre som grave e agudo?", opcoes: ["O volume", "A frequência (Grosso/Fino)", "A duração", "A cor"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é harmonia?", opcoes: ["Sons tocados um de cada vez", "Sons tocados ao mesmo tempo de forma agradável", "Barulho", "Silêncio"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual instrumento angolano usa uma corda e uma cabaça?", opcoes: ["Piano", "Mungongo/Berimbau", "Flauta", "Xilofone"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "A música folclórica representa...?", opcoes: ["A cultura de um povo", "As notícias da rádio", "Os anúncios", "Apenas as crianças"], correta: 0, grupoClasse: "3", nivel: "basico" },

    // 4ª CLASSE (20 questões)
    { pergunta: "O que é a organologia?", opcoes: ["Estudo dos órgãos humanos", "Estudo dos instrumentos musicais", "Estudo das plantas", "Estudo das nuvens"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual destes é um compositor angolano famoso?", opcoes: ["Beethoven", "Rui Mingas", "Mozart", "Bach"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é um intervalo musical?", opcoes: ["A hora do lanche", "A distância entre duas notas", "O fim da música", "O silêncio"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a família do Saxofone?", opcoes: ["Metais", "Madeiras (Sopro)", "Percussão", "Cordas"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que significa 'Andante' na música?", opcoes: ["Correr muito", "Andar com calma (velocidade média)", "Parar", "Sentar"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é uma escala musical?", opcoes: ["Uma escada de subir", "Série de notas por ordem de altura", "Um instrumento de medida", "Uma cor"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a importância da música na Independência de Angola?", opcoes: ["Nenhuma", "Forma de resistência e união cultural", "Apenas para dançar", "Nada"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a acústica?", opcoes: ["Estudo dos instrumentos", "Estudo das propriedades do som", "Uma marca de rádio", "Um tipo de guitarra"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Como se chama a música feita para filmes?", opcoes: ["Banda Sonora", "Rádio", "Publicidade", "Noticiário"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o folclore angolano?", opcoes: ["Música estrangeira", "Músicas e danças tradicionais do povo", "Desenhos animados", "Teatro moderno"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual instrumento é o símbolo do Semba?", opcoes: ["Violino", "Violão/Dikanza", "Sintetizador", "Harpa"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o vibrato?", opcoes: ["Um instrumento", "Pequena oscilação na altura do som", "Um grito", "Uma pausa"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a função dos pratos na bateria?", opcoes: ["Comer", "Produzir sons metálicos/acentos", "Soprar", "Nada"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a polifonia?", opcoes: ["Um só som", "Várias vozes ou melodias ao mesmo tempo", "Silêncio", "Um rádio"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o nome da pessoa que repara instrumentos?", opcoes: ["Luthier", "Mecânico", "Padeiro", "Costureiro"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a música instrumental?", opcoes: ["Música só cantada", "Música tocada apenas por instrumentos", "Música sem ritmo", "Poesia"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual destes é um intervalo de oitava?", opcoes: ["Do a Re", "Do a Mi", "Do ao Do seguinte", "Re a Fa"], correta: 2, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o contrabaixo?", opcoes: ["Uma flauta pequena", "O maior e mais grave instrumento de cordas", "Um tambor", "Uma tecla"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a função do microfone?", opcoes: ["Diminuir o som", "Amplificar ou gravar o som", "Limpar o instrumento", "Ver a música"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a improvisação?", opcoes: ["Ler a partitura", "Criar música no momento", "Copiar o outro", "Parar de tocar"], correta: 1, grupoClasse: "4", nivel: "basico" },

    // 5ª CLASSE (20 questões)
    { pergunta: "O que é a história da música?", opcoes: ["Estudo do futuro", "Estudo da evolução da música no tempo", "Estudo das notas", "Estudo das letras"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o papel do som na comunicação?", opcoes: ["Nenhum", "Transmitir mensagens e emoções", "Só fazer barulho", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a etnomusicologia?", opcoes: ["Estudo das plantas", "Estudo da música em seu contexto cultural", "Estudo do rádio", "Estudo dos fios"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o sintetizador?", opcoes: ["Um piano antigo", "Instrumento eletrônico que gera sons", "Um violão", "Uma flauta"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a importância da preservação das línguas nacionais na música?", opcoes: ["Nenhuma", "Manter a identidade e riqueza cultural", "Dificultar o canto", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a música religiosa?", opcoes: ["Música de festa", "Música ligada a cultos e fé", "Música de rádio", "Publicidade"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a função da caixa de ressonância?", opcoes: ["Guardar comida", "Amplificar o som nos instrumentos", "Pesar o instrumento", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a harmonia vocal?", opcoes: ["Gritar alto", "Várias vozes cantando notas diferentes que combinam", "Cantar sozinho", "Não cantar"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a influência da música africana no mundo?", opcoes: ["Nenhuma", "Base para o Jazz, Blues e muitos ritmos modernos", "Só em África", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a música erudita?", opcoes: ["Música de rua", "Música clássica de alta complexidade", "Música eletrônica", "Pop"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a importância da percussão na identidade angolana?", opcoes: ["Nenhuma", "É o coração do nosso ritmo e tradição", "Só para barulho", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o arranjo musical?", opcoes: ["Limpar o palco", "Adaptação de uma música para diferentes instrumentos ou vozes", "A letra da música", "O preço"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual instrumento é fundamental no Kuduro?", opcoes: ["Harpa", "Sintetizadores/Bases eletrônicas", "Piano de cauda", "Violoncelo"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a notação musical moderna?", opcoes: ["Desenhos em cavernas", "O sistema de pauta e notas que usamos hoje", "Falar o som", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a função do produtor musical?", opcoes: ["Limpar o estúdio", "Coordenar a gravação e criação do som final", "Tocar bateria", "Vender bilhetes"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o folclore universal?", opcoes: ["Música de um país", "Músicas tradicionais de todos os povos do mundo", "Música pop", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a importância dos festivais de música?", opcoes: ["Gastar dinheiro", "Divulgar a cultura e promover o intercâmbio", "Só para barulho", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a meloterapia (música na saúde)?", opcoes: ["Uma dança", "Uso da música para ajudar no tratamento de doenças", "Um instrumento", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual instrumento representa o Leste de Angola (Lundas/Cokwe)?", opcoes: ["Piano", "Mbingue/Kissange", "Órgão", "Violino"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a rítmica avançada?", opcoes: ["Bater palmas simples", "Divisões complexas do tempo na música", "Não ter ritmo", "Dormir"], correta: 1, grupoClasse: "5", nivel: "basico" },

    // 6ª CLASSE (20 questões)
    { pergunta: "O que é a estética musical?", opcoes: ["Maquiagem dos músicos", "Filosofia que estuda a beleza e o sentido da música", "O preço dos CDs", "O lugar do show"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o impacto da tecnologia digital na música?", opcoes: ["Nenhum", "Facilitou a criação, gravação e distribuição global", "Piorou a música", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a propriedade intelectual (direitos de autor)?", opcoes: ["Direito de copiar tudo", "Proteção legal das criações dos músicos", "Um imposto novo", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a função social da música em Angola?", opcoes: ["Nenhuma", "Educação, preservação histórica e crítica social", "Só diversão", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a música contemporânea?", opcoes: ["Música antiga", "Música criada nos tempos atuais com novas linguagens", "Música clássica", "Fado"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a importância da orquestra sinfônica?", opcoes: ["Nenhuma", "Execução de grandes obras com alta diversidade tímbrica", "Só para barulho", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o contratempo na música?", opcoes: ["Atraso no concerto", "Som executado na parte fraca do tempo", "Uma nota errada", "Fim da música"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que caracteriza o estilo 'Afro-Jazz'?", opcoes: ["Só música americana", "Fusão do Jazz com ritmos e instrumentos africanos", "Música eletrônica", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a função da crítica musical?", opcoes: ["Falar mal de todos", "Análise e avaliação profissional de obras e shows", "Vender discos", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a harmonia funcional?", opcoes: ["Tocar por tocar", "Estudo das funções dos acordes na música", "Uma marca de piano", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o papel da música na integração da SADC?", opcoes: ["Nenhum", "União cultural e partilha de valores regionais", "Guerra", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a semiótica musical?", opcoes: ["Estudo das sementes", "Estudo dos significados e símbolos na música", "Um tipo de voz", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o instrumento mais versátil da atualidade?", opcoes: ["Flauta", "Teclado/Sintetizador", "Triângulo", "Cavaquinho"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a produção fonográfica?", opcoes: ["Fazer fotos", "O processo de criação de discos e ficheiros de áudio", "Plantar milho", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a importância de estudar solfejo?", opcoes: ["Nenhuma", "Desenvolver a leitura e percepção musical", "Aumentar a voz", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a música de vanguarda?", opcoes: ["Música que segue regras antigas", "Música que experimenta novos caminhos e quebra regras", "Música pop", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o futuro da música angolana?", opcoes: ["O esquecimento", "A modernização mantendo as raízes tradicionais", "O fim", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a musicologia?", opcoes: ["Tocar bem", "O estudo científico e acadêmico da música", "Ouvir rádio", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a importância da disciplina de Educação Musical na escola?", opcoes: ["Nenhuma", "Desenvolvimento cognitivo, sensibilidade e cultura", "Só para brincar", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é um virtuoso?", opcoes: ["Um músico iniciante", "Um músico com técnica e habilidade extraordinária", "Um instrumento novo", "Uma nota musical"], correta: 1, grupoClasse: "6", nivel: "basico" }
];
