// BancoPerguntasMatematica.js - MENONGUE EDUCA
window.BancoPerguntasMatematica = [
    // 1ª CLASSE (20 questões)
    { pergunta: "Quanto é 2 + 2?", opcoes: ["3", "4", "5", "6"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é o número que vem antes do 5?", opcoes: ["3", "4", "6", "2"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Tenho 3 laranjas e como 1. Quantas restam?", opcoes: ["1", "2", "3", "4"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quanto é 5 + 0?", opcoes: ["0", "5", "10", "50"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é o maior número: 8 ou 3?", opcoes: ["3", "8", "Igual", "Nenhum"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quanto é 3 + 2?", opcoes: ["4", "5", "6", "7"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quanto é 4 - 1?", opcoes: ["2", "3", "4", "5"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que vem depois do número 9?", opcoes: ["8", "10", "11", "12"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quanto é 1 + 4?", opcoes: ["3", "5", "6", "7"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quanto é 5 - 5?", opcoes: ["0", "1", "5", "10"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quantos dedos temos em uma mão?", opcoes: ["4", "5", "6", "10"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual número representa 'nada'?", opcoes: ["0", "1", "2", "3"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quanto é 1 + 1?", opcoes: ["1", "2", "3", "4"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quanto é 2 + 1?", opcoes: ["2", "3", "4", "5"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual número vem depois do 1?", opcoes: ["0", "2", "3", "4"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quanto é 4 + 4?", opcoes: ["6", "7", "8", "9"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quanto é 3 - 2?", opcoes: ["0", "1", "2", "3"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Se eu tenho 2 bolas e ganho mais 2, com quantas fico?", opcoes: ["2", "3", "4", "5"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é o número menor: 1 ou 9?", opcoes: ["1", "9", "São iguais", "Nenhum"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quanto é 2 + 3?", opcoes: ["4", "5", "6", "7"], correta: 1, grupoClasse: "1", nivel: "basico" },

    // 2ª CLASSE (20 questões)
    { pergunta: "Quanto é 10 + 10?", opcoes: ["10", "20", "30", "40"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 15 - 5?", opcoes: ["5", "10", "15", "20"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Uma dezena são quantas unidades?", opcoes: ["1", "10", "100", "12"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 2 vezes 3?", opcoes: ["5", "6", "7", "8"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é o dobro de 4?", opcoes: ["6", "8", "10", "12"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 20 + 5?", opcoes: ["20", "25", "30", "35"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 12 - 2?", opcoes: ["8", "10", "11", "12"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 2 x 4?", opcoes: ["6", "8", "10", "12"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é uma dúzia?", opcoes: ["10", "12", "14", "16"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é a metade de 10?", opcoes: ["2", "4", "5", "6"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 30 - 10?", opcoes: ["10", "20", "30", "40"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 5 + 5 + 5?", opcoes: ["10", "15", "20", "25"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é o número sucessor de 19?", opcoes: ["18", "20", "21", "22"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 10 + 5 + 2?", opcoes: ["15", "16", "17", "18"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual número é par?", opcoes: ["1", "3", "4", "5"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 20 - 20?", opcoes: ["0", "1", "10", "20"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Se uma mão tem 5 dedos, duas mãos têm quantos?", opcoes: ["5", "8", "10", "12"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o triplo de 2?", opcoes: ["4", "5", "6", "8"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 10 + 40?", opcoes: ["30", "40", "50", "60"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quanto é 18 - 8?", opcoes: ["8", "10", "12", "14"], correta: 1, grupoClasse: "2", nivel: "basico" },

    // 3ª CLASSE (20 questões)
    { pergunta: "Quanto é 25 + 25?", opcoes: ["40", "50", "60", "70"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 5 x 5?", opcoes: ["20", "25", "30", "35"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 100 - 50?", opcoes: ["30", "40", "50", "60"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 12 dividido por 2?", opcoes: ["4", "5", "6", "7"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é um triângulo?", opcoes: ["Tem 4 lados", "Tem 3 lados", "É redondo", "Não tem lados"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 30 + 70?", opcoes: ["80", "90", "100", "110"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 4 x 3?", opcoes: ["7", "10", "12", "14"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 15 ÷ 3?", opcoes: ["3", "4", "5", "6"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quantos minutos tem uma hora?", opcoes: ["30", "50", "60", "100"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 200 - 100?", opcoes: ["50", "100", "150", "200"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 10 x 3?", opcoes: ["13", "20", "30", "40"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o dobro de 15?", opcoes: ["25", "30", "35", "40"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 45 + 5?", opcoes: ["40", "50", "60", "70"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O número 100 tem quantas centenas?", opcoes: ["1", "10", "100", "0"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 20 ÷ 4?", opcoes: ["4", "5", "6", "10"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quantos meses tem um ano?", opcoes: ["10", "11", "12", "24"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 80 + 20?", opcoes: ["90", "100", "110", "120"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o triplo de 10?", opcoes: ["20", "30", "40", "50"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto é 60 - 30?", opcoes: ["20", "30", "40", "50"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é um quadrado?", opcoes: ["Tem 3 lados", "Tem 4 lados iguais", "É um círculo", "Não tem pontas"], correta: 1, grupoClasse: "3", nivel: "basico" },

    // 4ª CLASSE (20 questões)
    { pergunta: "Quanto é 12 x 10?", opcoes: ["100", "110", "120", "130"], correta: 2, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 500 + 500?", opcoes: ["900", "1000", "1100", "1200"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o triplo de 9?", opcoes: ["18", "21", "24", "27"], correta: 3, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 80 dividido por 2?", opcoes: ["30", "40", "50", "60"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Um ângulo reto tem quantos graus?", opcoes: ["45°", "90°", "180°", "360°"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 100 x 5?", opcoes: ["105", "500", "550", "1000"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 1000 - 1?", opcoes: ["900", "990", "999", "1001"], correta: 2, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 6 x 7?", opcoes: ["40", "42", "44", "48"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quantos centímetros tem um metro?", opcoes: ["10", "50", "100", "1000"], correta: 2, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 40 ÷ 5?", opcoes: ["6", "7", "8", "9"], correta: 2, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 150 + 150?", opcoes: ["200", "300", "400", "500"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 9 x 4?", opcoes: ["32", "34", "36", "38"], correta: 2, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a metade de 50?", opcoes: ["20", "25", "30", "35"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 200 x 2?", opcoes: ["300", "400", "500", "600"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 100 ÷ 4?", opcoes: ["20", "25", "30", "50"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 7 x 8?", opcoes: ["54", "56", "58", "60"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quantos milímetros tem um centímetro?", opcoes: ["1", "10", "100", "1000"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 450 + 50?", opcoes: ["400", "500", "550", "600"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 10 x 10?", opcoes: ["20", "100", "1000", "200"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quanto é 30 ÷ 3?", opcoes: ["3", "10", "15", "20"], correta: 1, grupoClasse: "4", nivel: "basico" },

    // 5ª CLASSE (20 questões)
    { pergunta: "Quanto é 150 x 2?", opcoes: ["250", "300", "350", "400"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 1000 - 250?", opcoes: ["650", "700", "750", "800"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é a raiz quadrada de 25?", opcoes: ["3", "4", "5", "6"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 1/2 de 100?", opcoes: ["25", "50", "75", "10"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é um quadrilátero?", opcoes: ["Figura de 3 lados", "Figura de 4 lados", "Figura redonda", "Figura de 5 lados"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 250 + 750?", opcoes: ["900", "1000", "1100", "1200"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 9 x 8?", opcoes: ["64", "70", "72", "81"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 120 ÷ 4?", opcoes: ["20", "30", "40", "50"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Um quilômetro tem quantos metros?", opcoes: ["100", "500", "1000", "2000"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é o valor de Pi (aproximado)?", opcoes: ["2,14", "3,14", "4,14", "5,14"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 20% de 200?", opcoes: ["20", "40", "50", "80"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 11 x 11?", opcoes: ["111", "121", "131", "141"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é a terça parte de 30?", opcoes: ["3", "10", "15", "20"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 2500 ÷ 2?", opcoes: ["1200", "1250", "1300", "1500"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é um hexágono?", opcoes: ["6 lados", "5 lados", "7 lados", "8 lados"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 10³ (10 ao cubo)?", opcoes: ["100", "300", "1000", "30"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 0,5 + 0,25?", opcoes: ["0,7", "0,75", "0,8", "1,0"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o perímetro de um quadrado de lado 3cm?", opcoes: ["6cm", "9cm", "12cm", "15cm"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 400 x 5?", opcoes: ["1500", "2000", "2500", "3000"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Quanto é 1/4 de 20?", opcoes: ["4", "5", "6", "10"], correta: 1, grupoClasse: "5", nivel: "basico" },

    // 6ª CLASSE (20 questões)
    { pergunta: "Quanto é 12% de 100?", opcoes: ["10", "12", "15", "20"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quanto é 0,5 + 0,5?", opcoes: ["0,10", "1,0", "1,5", "0,55"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual é a área de um quadrado de lado 5cm?", opcoes: ["10cm²", "20cm²", "25cm²", "30cm²"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quanto é 10 ao quadrado (10²)?", opcoes: ["20", "100", "1000", "50"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quanto é 3/4 de 100?", opcoes: ["25", "50", "75", "80"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o valor de X em 2x = 10?", opcoes: ["2", "5", "8", "10"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quanto é 1,5 x 2?", opcoes: ["2,0", "2,5", "3,0", "3,5"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o volume de um cubo de lado 2cm?", opcoes: ["4cm³", "6cm³", "8cm³", "10cm³"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quanto é 1000 ÷ 8?", opcoes: ["100", "120", "125", "150"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é um triângulo isósceles?", opcoes: ["3 lados iguais", "2 lados iguais", "Nenhum lado igual", "4 lados iguais"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quanto é a raiz quadrada de 81?", opcoes: ["7", "8", "9", "10"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o valor de 5!", opcoes: ["20", "60", "120", "150"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quanto é 1/5 de 500?", opcoes: ["50", "100", "150", "200"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é um ângulo agudo?", opcoes: ["Menor que 90°", "Igual a 90°", "Maior que 90°", "Igual a 180°"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quanto é 0,25 x 4?", opcoes: ["0,5", "1,0", "1,5", "2,0"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o mmc de 4 e 6?", opcoes: ["6", "10", "12", "24"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quanto é 2 elevado a 5 (2⁵)?", opcoes: ["10", "16", "32", "64"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a soma dos ângulos internos de um triângulo?", opcoes: ["90°", "180°", "270°", "360°"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Quanto é 75% de 200?", opcoes: ["100", "125", "150", "175"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é um número primo?", opcoes: ["Par", "Divisível por 2", "Divisível apenas por 1 e por ele mesmo", "Divisível por 3"], correta: 2, grupoClasse: "6", nivel: "basico" }
];
