// BancoPerguntasCienciasNatureza.js - MENONGUE EDUCA
window.BancoPerguntasCienciasNatureza = [
    // 1ª CLASSE (20 questões)
    { pergunta: "Qual destes animais dá leite?", opcoes: ["Galinha", "Vaca", "Peixe", "Cobra"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que as plantas precisam para crescer?", opcoes: ["Sumo", "Água e Sol", "Brinquedos", "Pedras"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Onde vivem os peixes?", opcoes: ["Na terra", "No ar", "Na água", "Nas árvores"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes é um sentido do corpo?", opcoes: ["Visão", "Sapato", "Cadeira", "Carro"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "A galinha nasce de onde?", opcoes: ["Da barriga", "Do ovo", "Da terra", "Da água"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Como se chama o animal que tem o corpo coberto de penas?", opcoes: ["Cão", "Gato", "Pássaro", "Peixe"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é o órgão que usamos para ouvir?", opcoes: ["Olho", "Nariz", "Ouvido", "Boca"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que protege o tronco de uma árvore?", opcoes: ["Folhas", "Flores", "Casca", "Frutos"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes animais rasteja?", opcoes: ["Cachorro", "Serpente", "Macaco", "Pássaro"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Onde o sol nasce?", opcoes: ["Norte", "Sul", "Nascente", "Poente"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a cor do céu num dia de sol?", opcoes: ["Verde", "Azul", "Preto", "Rosa"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes é um fruto?", opcoes: ["Pedra", "Maçã", "Lápis", "Papel"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quantos olhos tem uma pessoa?", opcoes: ["1", "2", "3", "4"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O cão é um animal de estimação?", opcoes: ["Sim", "Não", "Talvez", "Mora na floresta"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que usamos para comer?", opcoes: ["Ouvido", "Nariz", "Boca", "Pé"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "A água serve para quê?", opcoes: ["Beber", "Queimar", "Suajar", "Rasgar"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes animais é grande?", opcoes: ["Formiga", "Elefante", "Abelha", "Pulga"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que usamos para ver as cores?", opcoes: ["Mãos", "Olhos", "Língua", "Pés"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "As flores cheiram bem por causa do nosso...?", opcoes: ["Tacto", "Olfato", "Paladar", "Visão"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Onde as raízes das plantas ficam?", opcoes: ["No ar", "Na terra", "No sol", "Nas nuvens"], correta: 1, grupoClasse: "1", nivel: "basico" },

    // 2ª CLASSE (20 questões)
    { pergunta: "O que usamos para respirar?", opcoes: ["Estômago", "Pulmões", "Coração", "Fígado"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destes animais voa?", opcoes: ["Cachorro", "Pássaro", "Gato", "Porco"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "As árvores são seres vivos?", opcoes: ["Não", "Sim", "Às vezes", "Não sei"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O sol é uma estrela?", opcoes: ["Sim", "Não", "É um planeta", "É a lua"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que acontece se não regarmos uma planta?", opcoes: ["Ela cresce mais", "Ela morre", "Ela muda de cor", "Nada"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é o principal órgão do sistema circulatório?", opcoes: ["Cérebro", "Coração", "Estômago", "Pulmão"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quantas patas tem um inseto (geralmente)?", opcoes: ["2", "4", "6", "8"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destes animais vive no deserto?", opcoes: ["Camelo", "Baleia", "Pinguim", "Urso"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é a cor das folhas da maioria das plantas?", opcoes: ["Azul", "Vermelho", "Verde", "Amarelo"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é o arco-íris?", opcoes: ["Um brinquedo", "Um fenómeno da luz", "Uma ponte", "Uma nuvem"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Onde o bebê se desenvolve antes de nascer?", opcoes: ["Na barriga da mãe", "Num ovo", "Na terra", "No hospital"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que o leão come?", opcoes: ["Erva", "Carne", "Fruta", "Sementes"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destes animais vive na água e na terra?", opcoes: ["Peixe", "Sapo", "Pássaro", "Gato"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que usamos para sentir o sabor?", opcoes: ["Nariz", "Orelha", "Língua", "Mão"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Como se chama o período em que dormimos?", opcoes: ["Dia", "Noite", "Tarde", "Almoço"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é o sentido que usamos para tocar nas coisas?", opcoes: ["Visão", "Audição", "Tacto", "Olfato"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que protege o cérebro?", opcoes: ["O crânio", "A pele", "O cabelo", "O chapéu"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual animal é conhecido como 'Rei da Selva'?", opcoes: ["Tigre", "Elefante", "Leão", "Zebra"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "De onde vem o leite?", opcoes: ["Da vaca", "Da galinha", "Da árvore", "Do rio"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que sai das nuvens quando chove?", opcoes: ["Pedras", "Água", "Fogo", "Vento"], correta: 1, grupoClasse: "2", nivel: "basico" },

    // 3ª CLASSE (20 questões)
    { pergunta: "O que é um animal carnívoro?", opcoes: ["Come erva", "Come carne", "Come fruta", "Não come"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Como se chama o movimento da Terra ao redor do Sol?", opcoes: ["Rotação", "Translação", "Salto", "Corrida"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é o maior planeta do sistema solar?", opcoes: ["Terra", "Marte", "Júpiter", "Saturno"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "A água no estado sólido é o quê?", opcoes: ["Vapor", "Gelo", "Líquido", "Chuva"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que protege o nosso corpo?", opcoes: ["A pele", "O cabelo", "As unhas", "A roupa"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual animal é um anfíbio?", opcoes: ["Jacaré", "Sapo", "Baleia", "Pombo"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que as abelhas produzem?", opcoes: ["Leite", "Mel", "Queijo", "Azeite"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Como se chama o satélite natural da Terra?", opcoes: ["Sol", "Marte", "Lua", "Vénus"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual gás respiramos?", opcoes: ["Hidrogénio", "Oxigénio", "Hélio", "Néon"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Onde se localiza o cérebro?", opcoes: ["No peito", "Na barriga", "Na cabeça", "Nas pernas"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é um animal herbívoro?", opcoes: ["Come carne", "Come plantas", "Come de tudo", "Não come"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o esqueleto?", opcoes: ["A pele", "O conjunto de ossos", "Os músculos", "O sangue"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é a principal função das raízes?", opcoes: ["Dar flores", "Fixar a planta e absorver água", "Fazer sombra", "Dar frutos"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o sistema digestivo?", opcoes: ["Serve para correr", "Serve para processar alimentos", "Serve para pensar", "Serve para ouvir"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a atmosfera?", opcoes: ["Água", "Ar que envolve a Terra", "Terra", "Fogo"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é a função do coração?", opcoes: ["Pensar", "Bombear sangue", "Respirar", "Comer"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que são animais vivíparos?", opcoes: ["Nascem de ovos", "Nascem da barriga da mãe", "Nascem da terra", "Não nascem"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quanto tempo a Terra demora para dar uma volta completa ao redor de si mesma?", opcoes: ["12 horas", "24 horas", "48 horas", "1 mês"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é um animal omnívoro?", opcoes: ["Come apenas carne", "Come apenas erva", "Come carne e plantas", "Não come nada"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a bússola?", opcoes: ["Um relógio", "Um instrumento de orientação", "Um brinquedo", "Uma ferramenta de cozinha"], correta: 1, grupoClasse: "3", nivel: "basico" },

    // 4ª CLASSE (20 questões)
    { pergunta: "O que é a fotossíntese?", opcoes: ["Respiração animal", "Produção de alimento das plantas", "Queda das folhas", "Crescimento de frutos"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual órgão bombeia o sangue?", opcoes: ["Cérebro", "Coração", "Pulmão", "Rins"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que são animais vertebrados?", opcoes: ["Têm ossos", "Não têm ossos", "Vivem na água", "Voam"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual gás os humanos precisam para respirar?", opcoes: ["Gás Carbónico", "Oxigénio", "Azoto", "Hélio"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Como se chama a parte da planta que fica debaixo da terra?", opcoes: ["Caule", "Folha", "Raiz", "Flor"], correta: 2, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é a temperatura de ebulição da água (ao nível do mar)?", opcoes: ["50°C", "80°C", "100°C", "150°C"], correta: 2, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é um ecossistema?", opcoes: ["Um grupo de pedras", "Seres vivos e o ambiente", "Uma cidade", "O céu"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual animal é um réptil?", opcoes: ["Sapo", "Cobra", "Peixe", "Macaco"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que são animais ovíparos?", opcoes: ["Nascem da barriga", "Nascem de ovos", "Não nascem", "Vivem no gelo"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Quantos planetas existem no sistema solar?", opcoes: ["7", "8", "9", "10"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a cadeia alimentar?", opcoes: ["Uma loja de comida", "A relação de alimentação entre seres", "Um tipo de metal", "Uma plantação"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a função dos rins?", opcoes: ["Bombear sangue", "Filtrar o sangue", "Digerir comida", "Pensar"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o estado gasoso da água?", opcoes: ["Gelo", "Vapor", "Líquido", "Neve"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o maior osso do corpo humano?", opcoes: ["Rádio", "Fémur", "Crânio", "Costela"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a polinização?", opcoes: ["Corte de árvores", "Transporte de pólen entre flores", "Rega das plantas", "Colheita de frutos"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que são animais invertebrados?", opcoes: ["Têm coluna vertebral", "Não têm coluna vertebral", "Têm penas", "São mamíferos"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o centro do sistema solar?", opcoes: ["Terra", "Lua", "Sol", "Júpiter"], correta: 2, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a função do sistema respiratório?", opcoes: ["Correr", "Trocas gasosas (respirar)", "Pensar", "Sentir"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a reciclagem?", opcoes: ["Jogar lixo no chão", "Transformar lixo em novos produtos", "Queimar plásticos", "Cortar árvores"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Como se chama o movimento da Terra que dá origem às estações do ano?", opcoes: ["Rotação", "Translação", "Oscilação", "Vibração"], correta: 1, grupoClasse: "4", nivel: "basico" },

    // 5ª CLASSE (20 questões)
    { pergunta: "O que é um ecossistema?", opcoes: ["Um conjunto de seres vivos e o ambiente", "Uma fábrica", "Uma floresta sem animais", "O espaço sideral"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é a estrela mais próxima da Terra?", opcoes: ["Lua", "Sol", "Estrela Polar", "Vénus"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que causa a erosão do solo?", opcoes: ["Vento e Água", "Plantas", "Animais", "Sol"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é o satélite natural da Terra?", opcoes: ["Sol", "Marte", "Lua", "Júpiter"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a poluição?", opcoes: ["Cuidar da natureza", "Sujeira e danos ao ambiente", "Plantar árvores", "Limpar o rio"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é o maior oceano da Terra?", opcoes: ["Atlântico", "Índico", "Pacífico", "Ártico"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o ciclo da água?", opcoes: ["A água parada", "O movimento da água na Terra", "A água da chuva apenas", "A água que bebemos"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é a função do esqueleto?", opcoes: ["Digerir comida", "Sustentar o corpo", "Fazer o sangue circular", "Respirar"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é um animal herbívoro?", opcoes: ["Come carne", "Come plantas", "Come de tudo", "Não come"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Como se chama a camada de ar da Terra?", opcoes: ["Litosfera", "Hidrosfera", "Atmosfera", "Biosfera"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é a função dos estômatos nas folhas?", opcoes: ["Proteção", "Trocas gasosas", "Absorção de água", "Crescimento"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o sistema nervoso?", opcoes: ["Coordena o corpo e os sentidos", "Faz o sangue circular", "Digeira os alimentos", "Produz hormonas"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é a principal função da clorofila?", opcoes: ["Cor das flores", "Atrair insetos", "Absorver luz solar para fotossíntese", "Proteger a raiz"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é um recurso renovável?", opcoes: ["Acaba se usarmos muito", "Pode ser reposto pela natureza", "Não existe em Angola", "É perigoso"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que são fungos?", opcoes: ["Plantas verdes", "Animais pequenos", "Seres que decompõem matéria orgânica", "Minerais"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é a função das plaquetas no sangue?", opcoes: ["Transportar oxigénio", "Cicatrizar feridas", "Defender o corpo", "Dar cor ao sangue"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Como se chama o instrumento que mede a temperatura?", opcoes: ["Balança", "Fita métrica", "Termómetro", "Cronómetro"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a biosfera?", opcoes: ["Conjunto de toda a vida na Terra", "Apenas o fundo do mar", "Apenas o topo das montanhas", "O espaço sem vida"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a função do intestino grosso?", opcoes: ["Digerir proteínas", "Absorver água e formar fezes", "Bombear sangue", "Respirar"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a gravidade?", opcoes: ["Uma doença", "Uma força que atrai os objetos para o centro da Terra", "Um tipo de luz", "O nome de um planeta"], correta: 1, grupoClasse: "5", nivel: "basico" },

    // 6ª CLASSE (20 questões)
    { pergunta: "Qual é a principal função dos glóbulos brancos?", opcoes: ["Transportar oxigénio", "Defender o corpo", "Produzir energia", "Digerir comida"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a atmosfera?", opcoes: ["A água da terra", "A camada de ar que envolve a terra", "O solo", "O núcleo da terra"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o sistema digestivo?", opcoes: ["Transforma comida em energia", "Faz o sangue circular", "Controla os movimentos", "Faz-nos respirar"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual é the principal fonte de energia da Terra?", opcoes: ["Vento", "Sol", "Eletricidade", "Petróleo"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a seleção natural?", opcoes: ["Teoria da evolução", "Um jogo", "Um tipo de comida", "Uma planta"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que são fontes de energia renováveis?", opcoes: ["Acabam rápido", "Não se esgotam", "Poluem muito", "São caras"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual é o maior órgão do corpo humano?", opcoes: ["Fígado", "Pele", "Cérebro", "Coração"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o efeito estufa?", opcoes: ["Um jardim", "Aquecimento da atmosfera", "Um tipo de casa", "Frio extremo"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual é a unidade básica da vida?", opcoes: ["Átomo", "Célula", "Tecido", "Órgão"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o ADN?", opcoes: ["Material genético", "Um tipo de carro", "Uma comida", "Um país"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual é a função do sistema endócrino?", opcoes: ["Mover o corpo", "Produzir hormonas", "Digerir gorduras", "Ouvir sons"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a biodiversidade?", opcoes: ["Apenas plantas", "Variedade de formas de vida", "Um parque de diversões", "Um tipo de solo"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que são máquinas simples?", opcoes: ["Computadores", "Alavancas e roldanas", "Carros elétricos", "Televisores"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a matéria?", opcoes: ["Apenas pedras", "Tudo o que tem massa e ocupa espaço", "O nada", "Um sentimento"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a função do pâncreas?", opcoes: ["Respirar", "Produzir insulina", "Pensar", "Ouvir"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a puberdade?", opcoes: ["Um país", "Fase de mudanças no corpo para a idade adulta", "Uma doença antiga", "O nome de uma fruta"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é um átomo?", opcoes: ["Uma estrela grande", "A menor partícula da matéria", "Um tipo de vírus", "Uma parte do pé"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a sustentabilidade?", opcoes: ["Gastar tudo hoje", "Usar recursos sem esgotá-los para o futuro", "Cortar todas as florestas", "Poluir os rios"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a função das artérias?", opcoes: ["Levar sangue do coração para o corpo", "Levar sangue ao coração", "Digerir açúcar", "Filtrar ar"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o sistema imunológico?", opcoes: ["Faz-nos dormir", "Defesa do corpo contra doenças", "Controla o peso", "Dá cor aos olhos"], correta: 1, grupoClasse: "6", nivel: "basico" }
];
