// BancoPerguntasGeografia.js - MENONGUE EDUCA
window.BancoPerguntasGeografia = [
    // 1ª CLASSE (20 questões)
    { pergunta: "O que mostra um mapa?", opcoes: ["Brinquedos", "Lugares e caminhos", "Comida", "Animais"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Onde o sol nasce?", opcoes: ["Norte", "Sul", "Nascente (Este)", "Poente (Oeste)"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a cor da terra na nossa horta?", opcoes: ["Azul", "Castanha/Preta", "Rosa", "Branca"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Onde vivemos?", opcoes: ["Na lua", "Na Terra", "No sol", "Nas estrelas"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes é um lugar da escola?", opcoes: ["Quarto", "Sala de aula", "Cozinha de casa", "Casa de banho pública"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Como se chama o caminho que fazemos para a escola?", opcoes: ["Itinerário", "Viagem", "Voo", "Salto"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Onde guardamos os livros na escola?", opcoes: ["No chão", "Na estante/armário", "No rio", "Na árvore"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a forma da Terra?", opcoes: ["Quadrada", "Redonda (Esférica)", "Triangular", "Plana"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que é uma montanha?", opcoes: ["Um buraco", "Uma terra muito alta", "Um rio", "Uma casa"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Onde o sol se põe?", opcoes: ["Norte", "Sul", "Nascente", "Poente (Oeste)"], correta: 3, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual a cor da água limpa no mapa?", opcoes: ["Verde", "Azul", "Vermelho", "Amarelo"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que é um bairro?", opcoes: ["Uma cidade inteira", "Uma parte da cidade", "Um país", "Um deserto"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Como se chama o lugar onde os aviões aterram?", opcoes: ["Porto", "Aeroporto", "Estação", "Paragem"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que usamos para ver lugares de muito longe?", opcoes: ["Lupa", "Binóculos", "Espelho", "Lápis"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes é um elemento da natureza?", opcoes: ["Carro", "Árvore", "Televisão", "Telemóvel"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que é uma ilha?", opcoes: ["Terra cercada de água", "Um rio", "Uma montanha", "Uma estrada"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Como se chama a nossa cidade?", opcoes: ["Luanda", "Menongue", "Lobito", "Malanje"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O que é o horizonte?", opcoes: ["A linha onde o céu e a terra parecem se tocar", "Um tipo de comida", "Um animal", "Uma cor"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destes animais vive na floresta angolana?", opcoes: ["Pinguim", "Palanca Negra", "Urso Polar", "Canguru"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Para que serve a bússola?", opcoes: ["Para comer", "Para orientação", "Para ouvir música", "Para ver as horas"], correta: 1, grupoClasse: "1", nivel: "basico" },

    // 2ª CLASSE (20 questões)
    { pergunta: "O que é uma aldeia?", opcoes: ["Lugar pequeno no campo", "Uma cidade grande", "Um prédio", "Um rio"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é um rio?", opcoes: ["Água parada", "Água corrente", "Água de poço", "Água de garrafa"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destes é um transporte aquático?", opcoes: ["Carro", "Avião", "Barco", "Mota"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é o clima?", opcoes: ["O estado do tempo", "Um tipo de solo", "Uma planta", "Um animal"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Onde se localiza Angola?", opcoes: ["Europa", "África", "América", "Ásia"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é uma estrada?", opcoes: ["Caminho para carros", "Lugar para nadar", "Lugar para voar", "Lugar para dormir"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o nome do nosso oceano?", opcoes: ["Índico", "Atlântico", "Pacífico", "Antártico"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é o relevo?", opcoes: ["As formas da terra", "As cores da terra", "O tamanho da terra", "O cheiro da terra"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é a fauna?", opcoes: ["Plantas", "Animais", "Pedras", "Nuvens"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é a flora?", opcoes: ["Animais", "Plantas", "Rios", "Montanhas"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é um vale?", opcoes: ["Terra alta", "Terra baixa entre montanhas", "Um rio", "Um lago"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual a capital de Angola?", opcoes: ["Menongue", "Luanda", "Lubango", "Benguela"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é a fronteira?", opcoes: ["Uma casa", "Linha que separa países ou províncias", "Um rio pequeno", "Uma ponte"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é um deserto?", opcoes: ["Lugar com muita água", "Lugar muito seco com areia", "Uma floresta", "Uma horta"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é o maior rio de Angola?", opcoes: ["Rio Zambeze", "Rio Kwanza", "Rio Cunene", "Rio Zaire"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é a agricultura?", opcoes: ["Criação de peixes", "Cultivo da terra", "Caça", "Construção"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Como se chama o movimento da terra sobre si mesma?", opcoes: ["Translação", "Rotação", "Salto", "Corrida"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que o globo terrestre representa?", opcoes: ["Uma bola de futebol", "O planeta Terra", "A lua", "O sol"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é a foz de um rio?", opcoes: ["Onde o rio nasce", "Onde o rio termina", "O meio do rio", "Uma ponte"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que é a nascente de um rio?", opcoes: ["Onde o rio morre", "Onde o rio começa", "Onde tem peixes", "Onde tem barcos"], correta: 1, grupoClasse: "2", nivel: "basico" },

    // 3ª CLASSE (20 questões)
    { pergunta: "Qual a província sede do governo de Angola?", opcoes: ["Benguela", "Luanda", "Huambo", "Bié"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o equador?", opcoes: ["Um país", "Linha imaginária que divide a terra em dois", "Um rio", "Uma montanha"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Quais são os pontos cardeais?", opcoes: ["Cima e Baixo", "Norte, Sul, Este e Oeste", "Frente e Trás", "Esquerda e Direita"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a cartografia?", opcoes: ["Estudo dos carros", "Estudo e desenho de mapas", "Estudo das pedras", "Estudo dos animais"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é o maior continente da Terra?", opcoes: ["África", "Ásia", "Europa", "América"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a hidrografia?", opcoes: ["Estudo do solo", "Estudo das águas", "Estudo do ar", "Estudo das plantas"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o oceano que banha Angola?", opcoes: ["Pacífico", "Atlântico", "Índico", "Glacial"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o clima tropical?", opcoes: ["Clima frio", "Clima quente e húmido", "Clima de neve", "Clima seco"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que são recursos naturais?", opcoes: ["Brinquedos", "Elementos da natureza usados pelo homem", "Carros", "Roupas"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a população?", opcoes: ["Conjunto de árvores", "Conjunto de pessoas de um lugar", "Conjunto de animais", "Conjunto de casas"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual a importância das matas?", opcoes: ["Nenhuma", "Produção de oxigénio e proteção da terra", "Fazer fogo", "Nada"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a erosão?", opcoes: ["Plantar árvores", "Desgaste do solo", "Limpar o rio", "Construir casas"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é o vento?", opcoes: ["Água parada", "Ar em movimento", "Fogo", "Terra"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a escala num mapa?", opcoes: ["Uma régua", "Relação entre o tamanho real e o desenho", "Uma cor", "Um nome"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é a maior província de Angola em área?", opcoes: ["Luanda", "Moxico", "Cuando Cubango", "Huíla"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a migração?", opcoes: ["Ficar no mesmo lugar", "Deslocação de pessoas", "Dormir", "Cantar"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a pecuária?", opcoes: ["Cultivo de milho", "Criação de animais", "Pesca", "Indústria"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é o ponto mais alto de Angola?", opcoes: ["Morro do Moco", "Serra da Leba", "Monte Kilimanjaro", "Everest"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é a poluição?", opcoes: ["Limpeza", "Sujeira e danos ao ambiente", "Saúde", "Alegria"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Para que serve a legenda de um mapa?", opcoes: ["Para decorar", "Explica o significado dos símbolos", "Para esconder o mapa", "Não serve para nada"], correta: 1, grupoClasse: "3", nivel: "basico" },

    // 4ª CLASSE (20 questões)
    { pergunta: "Quantas províncias tem Angola?", opcoes: ["10", "15", "18", "21"], correta: 3, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Em que continente fica Angola?", opcoes: ["África", "Europa", "América", "Ásia"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o rio mais longo de Angola?", opcoes: ["Rio Cunene", "Rio Kwanza", "Rio Zaire", "Rio Zambeze"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a densidade populacional?", opcoes: ["Peso das pessoas", "Habitantes por km²", "Tamanho das casas", "Riqueza"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o clima predominante em Angola?", opcoes: ["Frio", "Tropical", "Polar", "Temperado"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o êxodo rural?", opcoes: ["Ir da cidade para o campo", "Ir do campo para a cidade", "Viajar para fora", "Ficar em casa"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a importância econômica do petróleo para Angola?", opcoes: ["Nenhuma", "Principal fonte de receitas", "Serve para beber", "Nada"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a latitude?", opcoes: ["Distância ao Equador", "Distância ao mar", "Altura", "Peso"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a longitude?", opcoes: ["Altura", "Distância ao Meridiano de Greenwich", "Cor do solo", "Clima"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que são bacias hidrográficas?", opcoes: ["Banheiras grandes", "Área drenada por um rio principal e seus afluentes", "Lagos", "Rios secos"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a província com mais diamantes?", opcoes: ["Luanda", "Lunda Norte", "Huambo", "Benguela"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a biosfera?", opcoes: ["Camada de ar", "Esfera da vida", "Camada de pedras", "Água"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o país que faz fronteira ao sul com Angola?", opcoes: ["Congo", "Namíbia", "Zâmbia", "África do Sul"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o desenvolvimento sustentável?", opcoes: ["Gastar tudo", "Usar sem esgotar para o futuro", "Poluir", "Desmatar"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a atmosfera?", opcoes: ["Água", "Camada de ar que envolve a terra", "Solo", "Nuvens apenas"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual a principal atividade econômica do Cuando Cubango?", opcoes: ["Indústria pesada", "Agricultura, pecuária e extração de madeira", "Turismo de neve", "Nada"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é a indústria?", opcoes: ["Plantar milho", "Transformação de matéria-prima", "Pesca", "Dormir"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é o comércio externo?", opcoes: ["Vender na rua", "Trocas entre países", "Trocas na família", "Nada"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que são fontes de energia renováveis?", opcoes: ["Acabam logo", "Não se esgotam (Sol, Vento)", "Poluem muito", "São caras"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o maior oceano do mundo?", opcoes: ["Atlântico", "Pacífico", "Índico", "Ártico"], correta: 1, grupoClasse: "4", nivel: "basico" },

    // 5ª CLASSE (20 questões)
    { pergunta: "O que estuda a Geografia Humana?", opcoes: ["Pedras", "A relação das pessoas com o espaço", "Só animais", "Só plantas"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o continente mais populoso?", opcoes: ["África", "Ásia", "Europa", "América"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a globalização?", opcoes: ["Integração mundial", "Fim do mundo", "Guerra", "Isolamento"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a urbanização?", opcoes: ["Crescimento das cidades", "Crescimento do campo", "Plantar árvores", "Fazer rios"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o IDH?", opcoes: ["Índice de Desenvolvimento Humano", "Imposto", "Rio", "Lugar"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que causa o aquecimento global?", opcoes: ["Frio", "Efeito estufa e poluição", "Plantar árvores", "Chuva"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a biodiversidade?", opcoes: ["Apenas uma planta", "Variedade de seres vivos", "Só animais", "Só humanos"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o maior país de África?", opcoes: ["Angola", "Argélia", "Nigéria", "Egipto"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o setor primário?", opcoes: ["Educação", "Agricultura e extração", "Indústria", "Comércio"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o setor secundário?", opcoes: ["Serviços", "Indústria", "Agricultura", "Saúde"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é o setor terciário?", opcoes: ["Mineração", "Comércio e serviços", "Lavra", "Fábrica"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a importância da bacia do Congo?", opcoes: ["Nenhuma", "Maior reserva de biodiversidade e água", "Só para deserto", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a desertificação?", opcoes: ["Virar floresta", "Degradação da terra em zonas secas", "Muita chuva", "Fazer neve"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a energia hidroelétrica?", opcoes: ["Vem do sol", "Vem da força da água", "Vem do vento", "Vem do carvão"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a energia eólica?", opcoes: ["Vem da água", "Vem do vento", "Vem da terra", "Vem do sol"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o papel da ONU na geografia mundial?", opcoes: ["Guerra", "Manter a paz e cooperação", "Vender carros", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é a cartografia digital?", opcoes: ["Mapas em papel", "Mapas em computadores e GPS", "Desenhos à mão", "Nada"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual a função do GPS?", opcoes: ["Para comer", "Localização precisa no espaço", "Para ouvir rádio", "Para ver TV"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que são países desenvolvidos?", opcoes: ["Pobres", "Alta tecnologia e qualidade de vida", "Sem hospitais", "Sem escolas"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que são países emergentes?", opcoes: ["Países em rápido crescimento", "Países que estão a afundar", "Países sem ninguém", "Nada"], correta: 0, grupoClasse: "5", nivel: "basico" },

    // 6ª CLASSE (20 questões)
    { pergunta: "O que estuda a Geopolítica?", opcoes: ["Pedras", "Relação entre poder político e o espaço", "Só mapas", "Só climas"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a integração regional?", opcoes: ["Guerra entre vizinhos", "União de países de uma região (ex: UA, SADC)", "Isolamento", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o objetivo da SADC?", opcoes: ["Dividir África", "Desenvolvimento e cooperação na África Austral", "Fazer guerra", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o desenvolvimento humano?", opcoes: ["Só ter dinheiro", "Saúde, educação e qualidade de vida", "Ter carros", "Ser alto"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o impacto das alterações climáticas?", opcoes: ["Melhora o tempo", "Eventos extremos e danos ao ambiente", "Nada", "Mais gelo em Angola"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a soberania territorial?", opcoes: ["Ser mandado por outro", "Poder do Estado sobre seu território", "Não ter leis", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que são recursos estratégicos?", opcoes: ["Lixo", "Recursos vitais (água, energia, minerais)", "Brinquedos", "Papéis"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o papel de Angola na África Austral?", opcoes: ["Nenhum", "Líder regional e produtor de energia", "Apenas observa", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o desenvolvimento económico?", opcoes: ["Ficar pobre", "Aumento da produção e riqueza de um país", "Gastar tudo", "Não trabalhar"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a balança comercial positiva?", opcoes: ["Vender menos que compra", "Vender mais do que compra", "Não vender nada", "Não comprar nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a industrialização?", opcoes: ["Voltar ao campo", "Aumento das fábricas e tecnologia", "Fim das cidades", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que são direitos territoriais?", opcoes: ["Direito de brincar", "Direito de um povo sobre sua terra", "Não ter terra", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o planeamento urbano?", opcoes: ["Construir em qualquer lado", "Organização e crescimento planeado das cidades", "Destruir casas", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a importância das energias renováveis para o futuro?", opcoes: ["Nenhuma", "Redução da poluição e sustentabilidade", "Poluir mais", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a segurança alimentar?", opcoes: ["Comer veneno", "Garantia de comida saudável para todos", "Não ter comida", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é o turismo sustentável?", opcoes: ["Destruir a natureza", "Viajar respeitando o ambiente e cultura local", "Jogar lixo no rio", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o impacto da tecnologia na geografia?", opcoes: ["Nenhum", "Melhor mapeamento e conexão global", "Piora a vida", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a infraestrutura de um país?", opcoes: ["Apenas casas", "Rede de transportes, energia e comunicações", "Apenas árvores", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é a cooperação internacional?", opcoes: ["Guerra", "Ajuda e trabalho entre países", "Ódio", "Isolamento"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o maior desafio da geografia angolana?", opcoes: ["Falta de sol", "Desenvolvimento equilibrado de todas as províncias", "Ter muita água", "Nada"], correta: 1, grupoClasse: "6", nivel: "basico" }
];
