// BancoPerguntasPortugues.js - MENONGUE EDUCA
window.BancoPerguntasPortugues = [
    // 1ª CLASSE (20 questões)
    { pergunta: "Qual é a primeira letra da palavra 'Angola'?", opcoes: ["B", "A", "C", "D"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Complete: A, B, C, ...", opcoes: ["D", "E", "F", "G"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Como se escreve o nome da nossa cidade?", opcoes: ["Luanda", "Menongue", "Benguela", "Huambo"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a vogal na palavra 'SOL'?", opcoes: ["S", "O", "L", "A"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quantas letras tem a palavra 'BOI'?", opcoes: ["2", "3", "4", "5"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destas palavras começa com 'M'?", opcoes: ["Casa", "Mesa", "Bola", "Dado"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a letra final de 'TATU'?", opcoes: ["A", "E", "I", "U"], correta: 3, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Escolha a palavra correta: 'O ___ late'", opcoes: ["Gato", "Cão", "Pato", "Boi"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a letra que vem depois do 'F'?", opcoes: ["E", "G", "H", "I"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é a última letra do alfabeto?", opcoes: ["A", "Z", "X", "Y"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destas é uma vogal?", opcoes: ["B", "T", "E", "R"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "O nome 'Angola' começa com uma letra maiúscula?", opcoes: ["Sim", "Não", "Talvez", "Às vezes"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destas palavras rima com 'BOLA'?", opcoes: ["Cola", "Pato", "Cão", "Mão"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Como se chama o nosso país?", opcoes: ["Brasil", "Portugal", "Angola", "Namíbia"], correta: 2, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual é o som inicial de 'PATO'?", opcoes: ["Pa", "Ma", "Ba", "Ta"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quantas sílabas tem a palavra 'PÁ'?", opcoes: ["1", "2", "3", "4"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual o nome do objeto usado para escrever?", opcoes: ["Mesa", "Lápis", "Cadeira", "Porta"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "A palavra 'ANA' lida de trás para frente é igual?", opcoes: ["Sim", "Não", "Às vezes", "Não sei"], correta: 0, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Qual destas palavras é um animal?", opcoes: ["Uva", "Urso", "Unha", "Um"], correta: 1, grupoClasse: "1", nivel: "basico" },
    { pergunta: "Quantas vogais existem no alfabeto?", opcoes: ["3", "4", "5", "6"], correta: 2, grupoClasse: "1", nivel: "basico" },

    // 2ª CLASSE (20 questões)
    { pergunta: "Qual é o plural de 'Livro'?", opcoes: ["Livros", "Livres", "Livraria", "Livreado"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destas palavras é um nome próprio?", opcoes: ["Cadeira", "João", "Mesa", "Lápis"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é o feminino de 'Pai'?", opcoes: ["Irmã", "Tia", "Mãe", "Avó"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destas palavras rima com 'MÃO'?", opcoes: ["Pé", "Pão", "Dente", "Dedo"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quantas sílabas tem a palavra 'BOLA'?", opcoes: ["1", "2", "3", "4"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é o contrário de 'DIA'?", opcoes: ["Tarde", "Manhã", "Noite", "Sol"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destas palavras é um animal?", opcoes: ["Mesa", "Cão", "Carro", "Janela"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Como se escreve o número 2 por extenso?", opcoes: ["Um", "Dois", "Três", "Dez"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é a letra inicial de 'ESCOLA'?", opcoes: ["A", "E", "I", "O"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que o ponto final indica?", opcoes: ["Uma pergunta", "O fim de uma frase", "Uma surpresa", "Uma pausa curta"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é o sinónimo de 'Feliz'?", opcoes: ["Triste", "Contente", "Zangado", "Cansado"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quantas letras tem a palavra 'ESSE'?", opcoes: ["2", "3", "4", "5"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é o aumentativo de 'Gato'?", opcoes: ["Gatinho", "Gatão", "Gataria", "Gatada"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual é a sílaba tónica de 'BOLA'?", opcoes: ["BO", "LA", "B", "L"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destas palavras é um fruto?", opcoes: ["Banana", "Batata", "Cebola", "Arroz"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "O que usamos para separar as palavras na frase?", opcoes: ["Ponto", "Vírgula", "Espaço", "Traço"], correta: 2, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o plural de 'Pão'?", opcoes: ["Pãos", "Pães", "Pões", "Pãezinhos"], correta: 1, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual o antónimo de 'Quente'?", opcoes: ["Frio", "Morno", "Ardente", "Calor"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Qual destas palavras começa com 'H'?", opcoes: ["Homem", "Ovo", "Uva", "Ilha"], correta: 0, grupoClasse: "2", nivel: "basico" },
    { pergunta: "Quantas sílabas tem a palavra 'CADERNO'?", opcoes: ["1", "2", "3", "4"], correta: 2, grupoClasse: "2", nivel: "basico" },

    // 3ª CLASSE (20 questões)
    { pergunta: "Qual é o sinónimo de 'Bonito'?", opcoes: ["Feio", "Lindo", "Grande", "Pequeno"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é um substantivo?", opcoes: ["Uma ação", "Dá nome às coisas", "Uma característica", "Liga frases"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é the plural de 'Caneta'?", opcoes: ["Caneto", "Canetas", "Canetona", "Canetinha"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual destas palavras é um adjectivo?", opcoes: ["Correr", "Azul", "Mesa", "Nós"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Como se chama o conjunto de letras de A a Z?", opcoes: ["Números", "Alfabeto", "Símbolos", "Palavras"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é o feminino de 'Leão'?", opcoes: ["Leoa", "Gata", "Tigre", "Vaca"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual palavra está escrita correctamente?", opcoes: ["Caza", "Casa", "Kaza", "Cassa"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que significa 'antónimo'?", opcoes: ["Palavra igual", "Palavra contrária", "Palavra difícil", "Nome de pessoa"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual destas palavras indica uma acção?", opcoes: ["Pular", "Sapo", "Verde", "Ontem"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual é a sílaba tónica de 'CAFÉ'?", opcoes: ["CA", "FÉ", "Não tem", "CAF"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o coletivo de 'Cães'?", opcoes: ["Matilha", "Alcateia", "Cardume", "Vara"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o plural de 'Flor'?", opcoes: ["Flors", "Flores", "Florzinhas", "Florido"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "O que é um encontro consonantal?", opcoes: ["Vogais juntas", "Consoantes juntas", "Letras separadas", "Sílaba tónica"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o antónimo de 'Muitos'?", opcoes: ["Todos", "Poucos", "Vários", "Alguns"], correta: 1, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual destas palavras é um verbo?", opcoes: ["Cantar", "Canto", "Cantiga", "Cantor"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o gênero de 'Estudante'?", opcoes: ["Masculino", "Feminino", "Comum de dois", "Neutro"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual destas palavras tem um dígrafo?", opcoes: ["Carro", "Pato", "Boi", "Lua"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Como se chama a frase que faz uma pergunta?", opcoes: ["Afirmativa", "Exclamativa", "Interrogativa", "Negativa"], correta: 2, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual a sílaba tónica de 'LÁPIS'?", opcoes: ["LÁ", "PIS", "L", "P"], correta: 0, grupoClasse: "3", nivel: "basico" },
    { pergunta: "Qual o feminino de 'Cão'?", opcoes: ["Cãozinha", "Cadela", "Gata", "Loba"], correta: 1, grupoClasse: "3", nivel: "basico" },

    // 4ª CLASSE (20 questões)
    { pergunta: "Identifique o verbo na frase: 'O menino corre no parque'.", opcoes: ["Menino", "Corre", "Parque", "No"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o antónimo de 'Alto'?", opcoes: ["Largo", "Baixo", "Comprido", "Grosso"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o sujeito: 'Maria comprou um livro'?", opcoes: ["Maria", "Comprou", "Um livro", "Livro"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é um encontro vocálico?", opcoes: ["Duas consoantes juntas", "Duas vogais juntas", "Um ponto e uma vírgula", "Uma letra grande"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual palavra é um ditongo?", opcoes: ["Pai", "Saúde", "Rio", "Lua"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o pretérito de 'Eu estudo'?", opcoes: ["Eu estudarei", "Eu estudei", "Eu estudando", "Eu estudo"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Como se chama quem escreve poemas?", opcoes: ["Pintor", "Poeta", "Cantor", "Jogador"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual destas palavras é paroxítona?", opcoes: ["Café", "Escola", "Lâmpada", "Pé"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que indica a vírgula?", opcoes: ["Uma pergunta", "Uma pausa pequena", "O fim da frase", "Grito"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual é o aumentativo de 'Casa'?", opcoes: ["Casinha", "Casarão", "Casebre", "Casona"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o plural de 'Animal'?", opcoes: ["Animais", "Animals", "Animales", "Animalzinhos"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual palavra é oxítona?", opcoes: ["Mesa", "Urubu", "Caderno", "Lápis"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "O que é um substantivo próprio?", opcoes: ["Nome de objeto", "Nome de lugar ou pessoa", "Uma cor", "Uma ação"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o antónimo de 'Alegre'?", opcoes: ["Feliz", "Triste", "Rápido", "Bom"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual destas palavras tem acento agudo?", opcoes: ["Vovô", "Vovó", "Cão", "Mão"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o sujeito: 'O gato bebeu o leite'?", opcoes: ["Leite", "Bebeu", "O gato", "Gato"], correta: 2, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual destas é uma palavra composta?", opcoes: ["Beija-flor", "Pássaro", "Céu", "Flor"], correta: 0, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o feminino de 'Ator'?", opcoes: ["Atora", "Atriz", "Cantora", "Médica"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual destas palavras é um advérbio de tempo?", opcoes: ["Aqui", "Ontem", "Muito", "Não"], correta: 1, grupoClasse: "4", nivel: "basico" },
    { pergunta: "Qual o prefixo da palavra 'Infeliz'?", opcoes: ["In", "Feliz", "Iz", "Inf"], correta: 0, grupoClasse: "4", nivel: "basico" },

    // 5ª CLASSE (20 questões)
    { pergunta: "O que é um adjectivo?", opcoes: ["Indica ação", "Indica qualidade", "Indica tempo", "Indica lugar"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual frase está no futuro?", opcoes: ["Eu comi", "Eu como", "Eu comerei", "Eu comia"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual palavra é um advérbio de lugar?", opcoes: ["Ontem", "Muito", "Aqui", "Sim"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é um pronome pessoal?", opcoes: ["Eu", "Meu", "Este", "Quem"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual destas palavras é proparoxítona?", opcoes: ["Médico", "Papel", "Amor", "Coração"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual é o plural de 'Cidadão'?", opcoes: ["Cidadões", "Cidadães", "Cidadãos", "Cidadãos"], correta: 2, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é um texto narrativo?", opcoes: ["Dá instruções", "Conta uma história", "Faz uma propaganda", "É uma lista"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o colectivo de 'Peixes'?", opcoes: ["Alcateia", "Cardume", "Manada", "Enxame"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Identifique a preposição:", opcoes: ["Para", "Eu", "Bonito", "Correr"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual palavra tem 10 letras?", opcoes: ["Matemática", "Português", "Escola", "Livro"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o sinónimo de 'Habitar'?", opcoes: ["Mudar", "Viver/Morar", "Sair", "Construir"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é um verbo de ligação?", opcoes: ["Ser", "Falar", "Cantar", "Andar"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o feminino de 'Padrasto'?", opcoes: ["Madrinha", "Madrasta", "Mãe", "Tia"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o grau do adjectivo: 'Muito grande'?", opcoes: ["Comparativo", "Superlativo Absoluto", "Normal", "Diminutivo"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual palavra é invariável?", opcoes: ["Ontem", "Menino", "Bonito", "Nós"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o plural de 'Papel'?", opcoes: ["Papéis", "Papels", "Papeles", "Papeizinhos"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual destas palavras é um hiato?", opcoes: ["Saúde", "Peixe", "Noite", "Caixa"], correta: 0, grupoClasse: "5", nivel: "basico" },
    { pergunta: "O que é um artigo definido?", opcoes: ["Um", "O", "Uns", "Alguns"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual o plural de 'Giz'?", opcoes: ["Giz", "Gizes", "Gizs", "Gis"], correta: 1, grupoClasse: "5", nivel: "basico" },
    { pergunta: "Qual palavra indica posse?", opcoes: ["Meu", "Eu", "Aquele", "Quem"], correta: 0, grupoClasse: "5", nivel: "basico" },

    // 6ª CLASSE (20 questões)
    { pergunta: "O que é uma frase interrogativa?", opcoes: ["Afirma algo", "Faz uma pergunta", "Expressa surpresa", "Dá uma ordem"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual é o sujeito da frase: 'A escola de Menongue é bonita'?", opcoes: ["Bonita", "A escola de Menongue", "É", "Menongue"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é um verbo transitivo?", opcoes: ["Não precisa de complemento", "Precisa de complemento", "Indica estado", "É invariável"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o modo verbal que indica ordem?", opcoes: ["Indicativo", "Subjuntivo", "Imperativo", "Infinitivo"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é uma conjunção?", opcoes: ["Liga palavras ou frases", "Dá nome", "Indica qualidade", "Substitui o nome"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o antónimo de 'Efémero'?", opcoes: ["Curto", "Passageiro", "Duradouro", "Rápido"], correta: 2, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Identifique a voz passiva:", opcoes: ["O gato comeu o rato", "O rato foi comido pelo gato", "O gato come", "O rato foge"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual palavra é um hiato?", opcoes: ["Saída", "Caixa", "Peixe", "Noite"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é uma oração?", opcoes: ["Um conjunto de letras", "Uma frase com verbo", "Um título", "Uma palavra"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o grau superlativo de 'Bom'?", opcoes: ["Melhor", "Óptimo", "Boníssimo", "Mais bom"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual destas orações tem um predicado nominal?", opcoes: ["O aluno estuda", "O aluno é inteligente", "O aluno corre", "O aluno saiu"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é um advérbio de modo?", opcoes: ["Bem", "Hoje", "Lá", "Muito"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o plural de 'Mal'?", opcoes: ["Mals", "Males", "Malvados", "Mau"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual a função do sujeito?", opcoes: ["Indica a ação", "Pratica ou sofre a ação", "Dá qualidade", "Liga frases"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é um pronome relativo?", opcoes: ["Que", "Eu", "Meu", "Este"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o feminino de 'Poeta'?", opcoes: ["Poeta", "Poetisa", "Escritora", "Cantora"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual destas palavras é derivada?", opcoes: ["Pedra", "Pedreiro", "Mar", "Sol"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "O que é uma frase exclamativa?", opcoes: ["Pergunta algo", "Expressa emoção", "Dá ordem", "Afirma algo"], correta: 1, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o sinónimo de 'Analisar'?", opcoes: ["Examinar", "Fugir", "Comer", "Dormir"], correta: 0, grupoClasse: "6", nivel: "basico" },
    { pergunta: "Qual o antónimo de 'Guerra'?", opcoes: ["Luta", "Paz", "Conflito", "Batalha"], correta: 1, grupoClasse: "6", nivel: "basico" }
];
